/**
 * IronCrew — Lexware Office (formerly lexoffice) PackIntegrationAdapter.
 *
 * The Finance pack's one indispensable system. A German trade business that
 * asks "welche Rechnungen sind offen?" is asking about the voucherlist, and
 * every finance routine in Phase 4 — dunning, liquidity, receipt matching —
 * starts by reading it. Everything else the pack does is downstream of that
 * one list being correct.
 *
 * THE PRODUCT WAS RENAMED
 *
 * lexoffice became **Lexware Office**. The rebranding moved the API gateway
 * from `api.lexoffice.io` to `api.lexware.io` on 26 May 2025; the old gateway
 * was kept alive only until December 2025 and is gone. `developers.lexoffice.io`
 * still 301s to `developers.lexware.io`, which is why so much of the material
 * an operator finds by searching still says "lexoffice". The default base URL
 * here is the current one; `baseUrl` exists for sandboxes, not for nostalgia.
 *
 * Documentation: https://developers.lexware.io/docs/
 * (redirected from the older https://developers.lexoffice.io/docs/)
 *
 * WHAT THE DOCUMENTATION SAYS, AND THIS ADAPTER OBEYS
 *
 * - Auth is `Authorization: Bearer {accessToken}`; the key is generated by the
 *   owner at https://app.lexware.de/addons/public-api.
 * - Rate limit: **2 requests per second**, across all endpoints at once,
 *   enforced with a token bucket. Over it you get HTTP 429 and the call is not
 *   performed; a client that keeps hammering stays blocked. So the 429 message
 *   below names the actual number — "rate limited" alone tells an owner
 *   nothing about whether one routine or twenty is the problem.
 * - Endpoints used, all `GET`, all versioned `/v1`:
 *   `/v1/profile`, `/v1/voucherlist?voucherType=…&voucherStatus=…`,
 *   `/v1/invoices/{id}`.
 *
 * READ-ONLY, AND WHY THAT MATTERS MORE HERE THAN ANYWHERE ELSE
 *
 * This adapter has no create, no update, no delete, and no payment booking —
 * not "not yet", but by design. The other packs' adapters touch systems where
 * a mistaken write is an operational problem: a restarted VM, a wrong ticket
 * state, a duplicated calendar entry. Here a write is different in kind.
 * `POST /v1/invoices?finalize=true` produces a *legal* document in the
 * company's own books: an invoice with a gap-free number, a tax statement, and
 * a place in the GoBD-protected audit trail, which the owner is liable for and
 * cannot simply delete afterwards (it can only be cancelled by a further
 * document). The same goes for booking a payment against a voucher — that is a
 * bookkeeping assertion, not a note.
 *
 * Phase 4's finance work is supposed to reach the owner as an *approval* — a
 * draft, a proposed dunning letter, a list of what looks unpaid — not as a
 * fait accompli discovered later in the Steuerberater's export. An agent that
 * could call `POST /v1/invoices` would be one prompt injection away from
 * issuing invoices in a real company's name. Keeping the write verbs out of
 * the adapter means that risk cannot be reached by a bug, a bad prompt, or a
 * future caller who did not read this comment: the capability does not exist.
 *
 * THE HONEST LIMIT
 *
 * Unverified against a live Lexware Office account from this repository. The
 * URLs, headers, filter names and field names are taken from the published
 * documentation cited above and are asserted by the tests; whether a real
 * tenant answers is what `testConnection()` is for.
 */

import {
  integrationFetch,
  integrationJson,
  normaliseBaseUrl,
  PackIntegrationError,
  type IntegrationStatus,
  type PackIntegrationAdapter,
} from "../pack-integration.ts";

/** Current production gateway. The `/v1` segment is added by this adapter. */
export const LEXWARE_OFFICE_BASE_URL = "https://api.lexware.io";

/**
 * Documented cap, all endpoints together. Named so the 429 message can quote
 * it: an owner who is told "2 per second" can reason about their routines.
 */
export const LEXWARE_OFFICE_RATE_LIMIT_PER_SECOND = 2;

/** Documented default and maximum for the voucherlist page size. */
const DEFAULT_PAGE_SIZE = 25;
const MAX_PAGE_SIZE = 250;

export interface LexwareOfficeOptions {
  /** The Public-API key from https://app.lexware.de/addons/public-api. */
  apiKey: string;
  /** Gateway host, without the version segment. Defaults to the public API. */
  baseUrl?: string;
  /** Injectable for tests — defaults to the global fetch. */
  fetchImpl?: typeof fetch;
  /** Per-request timeout. Defaults to the shared 15s. */
  timeoutMs?: number;
}

/**
 * Voucher types the documentation lists today.
 *
 * The docs warn that new ones may appear, so this union constrains only what
 * *we* ask for. Responses are mapped as plain strings, so an unknown type that
 * turns up tomorrow flows through instead of being dropped.
 */
export type LexwareVoucherType =
  | "salesinvoice"
  | "salescreditnote"
  | "purchaseinvoice"
  | "purchasecreditnote"
  | "invoice"
  | "downpaymentinvoice"
  | "creditnote"
  | "orderconfirmation"
  | "quotation"
  | "deliverynote"
  | "any";

export type LexwareVoucherStatus =
  | "draft"
  | "open"
  | "paid"
  | "paidoff"
  | "voided"
  | "transferred"
  | "sepadebit"
  | "overdue"
  | "accepted"
  | "rejected"
  | "unchecked"
  | "any";

export interface LexwareVoucherQuery {
  /** Defaults to "any" — the voucherlist requires this filter. */
  types?: LexwareVoucherType[];
  /** Defaults to ["open"], which also surfaces the overdue ones. */
  status?: LexwareVoucherStatus[];
  archived?: boolean;
  contactId?: string;
  /** `yyyy-MM-dd`, e.g. "2026-01-01". */
  voucherDateFrom?: string;
  /** `yyyy-MM-dd`. */
  voucherDateTo?: string;
  voucherNumber?: string;
  /** 0-based. */
  page?: number;
  /** 1…250, default 25. */
  size?: number;
  /** e.g. "voucherDate,DESC". */
  sort?: string;
}

/** One row of the voucherlist: enough to answer "was ist offen?". */
export interface LexwareVoucher {
  id: string;
  /** Documented enum, carried as a string so a new type is not swallowed. */
  type?: string;
  status?: string;
  number?: string;
  /** RFC 3339 with offset, exactly as Lexware sent it. */
  date?: string;
  dueDate?: string;
  /** Total of the voucher, may include taxes. */
  totalAmount?: number;
  /** What is still unpaid. Null for drafts and most non-invoices. */
  openAmount?: number;
  /** "EUR" is the only documented value; carried through regardless. */
  currency?: string;
  contactId?: string;
  contactName?: string;
  archived?: boolean;
  /** True when Lexware itself flagged the row as overdue. */
  overdue: boolean;
}

export interface LexwareVoucherPage {
  vouchers: LexwareVoucher[];
  /** 0-based index of the page that was returned. */
  page: number;
  totalPages: number;
  totalElements: number;
  /** So a caller can page without re-deriving it from four fields. */
  hasMore: boolean;
}

export interface LexwareProfile {
  organizationId?: string;
  companyName?: string;
  /** "net", "gross" or "vatfree". */
  taxType?: string;
  /** Kleinunternehmer nach §19 UStG. */
  smallBusiness?: boolean;
  /** Who authorised this API connection, from `created.userName`. */
  connectedUser?: string;
  businessFeatures: string[];
}

export interface LexwareInvoiceLineItem {
  name?: string;
  quantity?: number;
  unitName?: string;
  /** `lineItemAmount` — the line's total in the voucher's tax mode. */
  amount?: number;
}

export interface LexwareInvoice {
  id: string;
  number?: string;
  status?: string;
  date?: string;
  createdDate?: string;
  updatedDate?: string;
  archived?: boolean;
  contactId?: string;
  contactName?: string;
  currency?: string;
  totalNetAmount?: number;
  totalGrossAmount?: number;
  totalTaxAmount?: number;
  /** "net", "gross" or one of the vatfree variants. */
  taxType?: string;
  /** e.g. "10 Tage - 3 %, 30 Tage netto". */
  paymentTermLabel?: string;
  title?: string;
  remark?: string;
  lineItems: LexwareInvoiceLineItem[];
}

export class LexwareOfficeAdapter implements PackIntegrationAdapter {
  readonly key = "lexware-office";
  readonly label = "Lexware Office";

  private readonly apiKey: string;
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly timeoutMs: number | undefined;

  constructor(opts: LexwareOfficeOptions) {
    // Trimmed, never validated for shape: guessing at a key format is how an
    // adapter rejects a perfectly good key after the vendor rotates it.
    this.apiKey = (opts.apiKey ?? "").trim();
    this.baseUrl = normaliseBaseUrl(opts.baseUrl ?? LEXWARE_OFFICE_BASE_URL);
    this.fetchImpl = opts.fetchImpl ?? fetch;
    this.timeoutMs = opts.timeoutMs;
  }

  /**
   * The cheapest authenticated call there is: no filters, no paging, and it
   * returns the company name, which is the one thing that tells an owner they
   * connected *their* account and not a test tenant they pasted a key from.
   */
  async testConnection(): Promise<IntegrationStatus> {
    try {
      const profile = await this.getProfile();
      const company = profile.companyName ?? "unbekannte Firma";
      const extra = profile.smallBusiness ? ", Kleinunternehmer nach §19 UStG" : "";
      return {
        ok: true,
        message: `Verbunden mit Lexware Office. Firma: „${company}“${extra}.`,
        // Not a product version — the API version this adapter speaks. Saying
        // "v1" is honest; inventing a release number would not be.
        version: "v1",
      };
    } catch (err) {
      // Reported, not thrown: the Settings panel asks "does this work?", and
      // an exception there is an outage in the page rather than an answer.
      return { ok: false, message: err instanceof Error ? err.message : String(err) };
    }
  }

  /** `GET /v1/profile` — company name, tax mode and who authorised the key. */
  async getProfile(): Promise<LexwareProfile> {
    const raw = await this.get<RawProfile>("/v1/profile", "Profil");
    return {
      organizationId: str(raw.organizationId),
      companyName: str(raw.companyName),
      taxType: str(raw.taxType),
      smallBusiness: typeof raw.smallBusiness === "boolean" ? raw.smallBusiness : undefined,
      connectedUser: str(raw.created?.userName),
      businessFeatures: Array.isArray(raw.businessFeatures)
        ? raw.businessFeatures.filter((f): f is string => typeof f === "string")
        : [],
    };
  }

  /**
   * `GET /v1/voucherlist` — the answer to "welche Rechnungen sind offen?".
   *
   * Defaults are chosen for exactly that question: every voucher type, status
   * `open`. The documentation notes that `overdue` is a *transient* status, so
   * a query for `open` already returns the vouchers whose due date has passed,
   * flagged as `overdue`. Filtering for `open` and getting both is the cheap
   * path; asking for `overdue` separately costs a second request against a
   * two-per-second budget.
   */
  async listVouchers(opts: LexwareVoucherQuery = {}): Promise<LexwareVoucherPage> {
    const params = new URLSearchParams();
    // Both filters are mandatory on this endpoint — omitting either is a 400,
    // so the defaults are part of the contract, not a convenience.
    params.set("voucherType", joinFilter(opts.types, "any"));
    params.set("voucherStatus", statusFilter(opts.status));
    if (opts.archived !== undefined) params.set("archived", String(opts.archived));
    if (opts.contactId) params.set("contactId", opts.contactId);
    if (opts.voucherDateFrom) params.set("voucherDateFrom", opts.voucherDateFrom);
    if (opts.voucherDateTo) params.set("voucherDateTo", opts.voucherDateTo);
    if (opts.voucherNumber) params.set("voucherNumber", opts.voucherNumber);
    if (opts.page !== undefined) params.set("page", String(Math.max(0, Math.trunc(opts.page))));
    params.set("size", String(boundedPageSize(opts.size)));
    if (opts.sort) params.set("sort", opts.sort);

    const raw = await this.get<RawVoucherPage>(`/v1/voucherlist?${params.toString()}`, "Belegliste");
    const rows = Array.isArray(raw.content) ? raw.content : [];
    const page = num(raw.number) ?? 0;
    const totalPages = num(raw.totalPages) ?? 0;
    return {
      vouchers: rows.map(toVoucher),
      page,
      totalPages,
      totalElements: num(raw.totalElements) ?? rows.length,
      // `last` is what the API actually asserts; the arithmetic is the
      // fallback for a response that omits it.
      hasMore: typeof raw.last === "boolean" ? !raw.last : page + 1 < totalPages,
    };
  }

  /** `GET /v1/invoices/{id}` — the detail behind one voucherlist row. */
  async getInvoice(id: string): Promise<LexwareInvoice> {
    const trimmed = (id ?? "").trim();
    if (trimmed === "") throw new PackIntegrationError("Lexware Office: Es wurde keine Rechnungs-ID angegeben.");
    // Encoded so a caller-supplied id can never grow a path segment or a query
    // string of its own.
    const raw = await this.get<RawInvoice>(`/v1/invoices/${encodeURIComponent(trimmed)}`, "Rechnung");
    return {
      id: str(raw.id) ?? trimmed,
      number: str(raw.voucherNumber),
      status: str(raw.voucherStatus),
      date: str(raw.voucherDate),
      createdDate: str(raw.createdDate),
      updatedDate: str(raw.updatedDate),
      archived: typeof raw.archived === "boolean" ? raw.archived : undefined,
      contactId: str(raw.address?.contactId),
      contactName: str(raw.address?.name),
      currency: str(raw.totalPrice?.currency),
      totalNetAmount: num(raw.totalPrice?.totalNetAmount),
      totalGrossAmount: num(raw.totalPrice?.totalGrossAmount),
      totalTaxAmount: num(raw.totalPrice?.totalTaxAmount),
      taxType: str(raw.taxConditions?.taxType),
      paymentTermLabel: str(raw.paymentConditions?.paymentTermLabel),
      title: str(raw.title),
      remark: str(raw.remark),
      lineItems: Array.isArray(raw.lineItems)
        ? raw.lineItems.map((item) => ({
            name: str(item?.name),
            quantity: num(item?.quantity),
            unitName: str(item?.unitName),
            amount: num(item?.lineItemAmount),
          }))
        : [],
    };
  }

  /**
   * The single request path. GET only — see the read-only note in the header;
   * there is deliberately no sibling that takes a method or a body.
   */
  private async get<T>(path: string, what: string): Promise<T> {
    if (this.apiKey === "") {
      // "Not configured" is an answer, and it is the answer an owner gets
      // before they have pasted a key at all.
      throw new PackIntegrationError(`${what}: Der API-Schlüssel für Lexware Office fehlt.`);
    }

    const res = await integrationFetch(
      this.fetchImpl,
      `${this.baseUrl}${path}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          Accept: "application/json",
        },
      },
      this.timeoutMs,
    );

    if (!res.ok) throw statusError(what, res.status);
    return await integrationJson<T>(res, `Lexware Office ${what}`);
  }
}

/**
 * Turns a status code into something an owner can act on.
 *
 * The body is never read for this message, and that is the point rather than
 * an oversight: Lexware's own documented 403 body echoes the Authorization
 * header back at you verbatim. An error string built from a response body
 * would carry the API key into every log line that touched it.
 */
function statusError(what: string, status: number): PackIntegrationError {
  const prefix = `Lexware Office ${what}`;
  switch (status) {
    case 400:
      return new PackIntegrationError(
        `${prefix}: Lexware Office hat die Anfrage abgelehnt (HTTP 400) — vermutlich ein ungültiger Filter- oder Datumswert.`,
        status,
      );
    case 401:
      return new PackIntegrationError(
        `${prefix}: Der API-Schlüssel wird von Lexware Office nicht akzeptiert (HTTP 401). ` +
          `Er ist ungültig, wurde widerrufen oder der API-Zugang ist deaktiviert. ` +
          `Neuen Schlüssel unter https://app.lexware.de/addons/public-api erzeugen.`,
        status,
      );
    case 402:
      return new PackIntegrationError(
        `${prefix}: Der Lexware-Vertrag dieses Kontos deckt diesen Zugriff nicht ab (HTTP 402).`,
        status,
      );
    case 403:
      return new PackIntegrationError(
        `${prefix}: Der API-Schlüssel hat für diesen Bereich keine Berechtigung (HTTP 403). ` +
          `Ältere Schlüssel enthalten neuere Bereiche nicht — einen neuen Schlüssel erzeugen.`,
        status,
      );
    case 404:
      return new PackIntegrationError(`${prefix}: Nicht gefunden (HTTP 404).`, status);
    case 429:
      return new PackIntegrationError(
        `${prefix}: Rate-Limit von Lexware Office erreicht (HTTP 429). ` +
          `Erlaubt sind ${LEXWARE_OFFICE_RATE_LIMIT_PER_SECOND} Anfragen pro Sekunde über alle Endpunkte zusammen; ` +
          `die Anfrage wurde nicht ausgeführt. Später erneut versuchen und die Aufrufe entzerren.`,
        status,
      );
    case 500:
      return new PackIntegrationError(
        `${prefix}: Serverfehler bei Lexware Office (HTTP 500). ` +
          `Laut Dokumentation steckt dahinter auch ein überschrittenes Rate-Limit ` +
          `(${LEXWARE_OFFICE_RATE_LIMIT_PER_SECOND} Anfragen pro Sekunde).`,
        status,
      );
    case 503:
      return new PackIntegrationError(`${prefix}: Lexware Office ist zurzeit nicht verfügbar (HTTP 503).`, status);
    case 504:
      return new PackIntegrationError(
        `${prefix}: Zeitüberschreitung im Lexware-Gateway nach 30 Sekunden (HTTP 504).`,
        status,
      );
    default:
      return new PackIntegrationError(`${prefix}: Unerwartete Antwort von Lexware Office (HTTP ${status}).`, status);
  }
}

/** A comma-separated filter list, or the documented catch-all "any". */
function joinFilter(values: string[] | undefined, fallback: string): string {
  const list = (values ?? []).map((v) => v.trim()).filter((v) => v !== "");
  if (list.length === 0) return fallback;
  // A list that already contains "any" means all of them; sending it alongside
  // siblings is at best redundant and at worst a 400.
  if (list.includes("any")) return "any";
  return [...new Set(list)].join(",");
}

/**
 * Same as `joinFilter`, plus the one rule the voucherlist enforces: `overdue`
 * cannot be combined with other statuses. Catching it here turns a confusing
 * HTTP 400 into a sentence that says what to do instead.
 */
function statusFilter(values: LexwareVoucherStatus[] | undefined): string {
  const joined = joinFilter(values, "open");
  const parts = joined.split(",");
  if (parts.includes("overdue") && parts.length > 1) {
    throw new PackIntegrationError(
      "Lexware Office: Der Status „overdue“ lässt sich nicht mit anderen Status kombinieren. " +
        "Eine Abfrage nach „open“ liefert überfällige Belege ohnehin mit.",
    );
  }
  return joined;
}

function boundedPageSize(size: number | undefined): number {
  if (size === undefined || !Number.isFinite(size)) return DEFAULT_PAGE_SIZE;
  return Math.min(MAX_PAGE_SIZE, Math.max(1, Math.trunc(size)));
}

/**
 * Dates stay the strings Lexware sent (RFC 3339 with an offset).
 *
 * Parsing them into a Date here would push a voucher dated
 * `2026-01-01T00:00:00.000+01:00` into the previous day for anyone rendering
 * in UTC — and a Beleg that moves across a month boundary is a wrong VAT
 * period, not a cosmetic bug.
 */
function toVoucher(row: RawVoucher): LexwareVoucher {
  const status = str(row?.voucherStatus);
  return {
    id: str(row?.id) ?? "",
    type: str(row?.voucherType),
    status,
    number: str(row?.voucherNumber),
    date: str(row?.voucherDate),
    dueDate: str(row?.dueDate),
    totalAmount: num(row?.totalAmount),
    openAmount: num(row?.openAmount),
    currency: str(row?.currency),
    contactId: str(row?.contactId),
    contactName: str(row?.contactName),
    archived: typeof row?.archived === "boolean" ? row.archived : undefined,
    overdue: status === "overdue",
  };
}

/** `null` is a documented value for several fields; it is "absent", not "". */
function str(value: unknown): string | undefined {
  return typeof value === "string" && value !== "" ? value : undefined;
}

/** Money arrives as a JSON number; anything else is absent, never coerced. */
function num(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

interface RawProfile {
  organizationId?: unknown;
  companyName?: unknown;
  taxType?: unknown;
  smallBusiness?: unknown;
  businessFeatures?: unknown;
  created?: { userName?: unknown } | null;
}

interface RawVoucher {
  id?: unknown;
  voucherType?: unknown;
  voucherStatus?: unknown;
  voucherNumber?: unknown;
  voucherDate?: unknown;
  dueDate?: unknown;
  totalAmount?: unknown;
  openAmount?: unknown;
  currency?: unknown;
  contactId?: unknown;
  contactName?: unknown;
  archived?: unknown;
}

interface RawVoucherPage {
  content?: RawVoucher[];
  last?: unknown;
  totalPages?: unknown;
  totalElements?: unknown;
  number?: unknown;
}

interface RawInvoice {
  id?: unknown;
  voucherNumber?: unknown;
  voucherStatus?: unknown;
  voucherDate?: unknown;
  createdDate?: unknown;
  updatedDate?: unknown;
  archived?: unknown;
  address?: { contactId?: unknown; name?: unknown } | null;
  totalPrice?: {
    currency?: unknown;
    totalNetAmount?: unknown;
    totalGrossAmount?: unknown;
    totalTaxAmount?: unknown;
  } | null;
  taxConditions?: { taxType?: unknown } | null;
  paymentConditions?: { paymentTermLabel?: unknown } | null;
  title?: unknown;
  remark?: unknown;
  lineItems?: Array<{ name?: unknown; quantity?: unknown; unitName?: unknown; lineItemAmount?: unknown }>;
}
