import { useI18n } from "../i18n";

/** Translate product-owned labels, never data keys or user-authored content. */
export const crewLabels: Record<string, string> = {
  Info: "Info",
  Warnung: "Warning",
  Kritisch: "Critical",
  Eingang: "Inbox",
  Geplant: "Planned",
  Bereit: "Ready",
  Zugewiesen: "Assigned",
  Läuft: "Running",
  Wartet: "Waiting",
  Blockiert: "Blocked",
  Review: "Review",
  "Freigabe nötig": "Approval required",
  Erledigt: "Done",
  Fehlgeschlagen: "Failed",
  Abgebrochen: "Cancelled",
  Offline: "Offline",
  "Denkt nach": "Thinking",
  Arbeitet: "Working",
  "Im Meeting": "In a meeting",
  "Wartet auf Eingabe": "Waiting for input",
  "Wartet auf Freigabe": "Waiting for approval",
  "Rate-Limit": "Rate limited",
  Pausiert: "Paused",
  Fehler: "Error",
  Aktiv: "Active",
  Erreicht: "Achieved",
  Aufgegeben: "Stopped",
  Entwurf: "Draft",
  Abgeschlossen: "Completed",
  Ausstehend: "Pending",
  Verpasst: "Missed",
  Notiz: "Note",
  Fakt: "Fact",
  Präferenz: "Preference",
  Hypothese: "Hypothesis",
  Zusammenfassung: "Summary",
  "E-Mail": "Email",
  Lesen: "Read",
  "Lesen + Senden": "Read + send",
  "Katalog (JSON)": "Catalog (JSON)",
  "MCP-Registry": "MCP registry",
  "Claude-Code-Marktplatz": "Claude Code marketplace",
  "Git-Repository": "Git repository",
  "MCP-Server": "MCP server",
  Chef: "Owner",
  Gast: "Guest",
  "wartet auf Freigabe": "waiting for approval",
  freigegeben: "approved",
  blockiert: "blocked",
  abgelehnt: "rejected",
  angewendet: "applied",
  fehlgeschlagen: "failed",
  überholt: "superseded",
  "neu anlegen": "create",
  ändern: "modify",
  löschen: "delete",
  wartet: "waiting",
  läuft: "running",
  erledigt: "done",
  aufgegeben: "stopped",
  abgebrochen: "cancelled",
  "Datei (NDJSON)": "File (NDJSON)",
  "HTTP-Collector": "HTTP collector",
  "beobachtet nur": "read only",
  "ändert den Arbeitsbereich": "modifies workspace",
  "wirkt nach außen": "external effects",
  eingebaut: "built in",
  Marktplatz: "Marketplace",
  Agent: "Agent",
  Projekt: "Project",
  Talent: "Talent",
  "über den Agenten": "via agent",
  "über das Projekt": "via project",
  "über das Talent": "via talent",
};

export function useCrewLabel() {
  const { language } = useI18n();
  return (label: string): string => (language === "de" ? label : (crewLabels[label] ?? label));
}
