import { integrationOutputSchema } from "./result-contracts.ts";
import { integrationPriceSchema, type IntegrationPrice, type MeteredIntegrationRequest } from "./pricing.ts";
import { googleWorkspaceCapabilities, executeGoogleWorkspace } from "./google-workspace.ts";
import type { OAuthConfiguration, OAuthTokenBroker } from "./oauth.ts";
import { sevdeskVoucherStageSchema, sevdeskVoucherBookSchema, voucherPayload } from "./sevdesk.ts";
import { randomUUID, createHash } from "node:crypto";
import { z } from "zod";
import {
  checkResponse,
  defaultTransport,
  IntegrationError,
  redact,
  type HttpRequest,
  type HttpResponse,
  type HttpTransport,
} from "./transport.ts";
import { type SecretRef, type SecretResolver } from "./secrets.ts";

export interface IntegrationScope {
  companyId: string;
  areaId: string;
  customerId?: string;
  projectId?: string;
}
export type IntegrationProvider =
  | "brave"
  | "research"
  | "nextcloud"
  | "gdrive"
  | "sevdesk"
  | "tactical"
  | "proxmox"
  | "graph"
  | "telegram"
  | "discord";
export interface IntegrationConnection {
  id: string;
  provider: IntegrationProvider;
  scope: IntegrationScope;
  /** Administrative origin/base, never an argument generated by an LLM. */
  baseUrl?: string;
  secretRef?: SecretRef;
  oauth?: OAuthConfiguration;
  pricing?: IntegrationPrice;
  username?: string;
  tokenId?: string;
  /** Restricted target account resources: folder IDs, agent IDs, node/VM IDs, user IDs or channel IDs. */
  resourceIds?: string[];
  rootPath?: string;
  enabledTools: string[];
  schemaTag: string;
  liveValidatedAt?: string;
  /** Plain HTTP only for an explicitly configured private fixture/connector. Public fetch ignores this. */
  allowHttp?: boolean;
}
export interface AuthorizedIntegrationAction {
  id: string;
  toolId: string;
  targetId: string;
  scope: IntegrationScope;
  args: unknown;
}
export interface IntegrationResult {
  observedAt: string;
  effectStatus: "succeeded" | "accepted";
  externalId?: string;
  evidenceRefs: string[];
  data: unknown;
}
export interface IntegrationCapability {
  id: string;
  provider: IntegrationProvider;
  effect: "read" | "external_draft" | "external_change" | "external_send";
  retryPolicy: "safe" | "reconcile_first" | "never_automatic";
  inputSchema: z.ZodType;
  outputSchema: z.ZodType;
  reconciliation: string;
  requiresApproval?: boolean;
}
const id = z
  .string()
  .min(1)
  .max(300)
  .regex(/^[A-Za-z0-9_@.!:-]+$/);
const empty = z.object({}).strict();
const page = z
  .object({ limit: z.number().int().min(1).max(100).optional(), offset: z.number().int().min(0).optional() })
  .strict();
const relative = z
  .string()
  .min(1)
  .max(1500)
  .refine(
    (value) =>
      !value.startsWith("/") &&
      !value.includes("\\") &&
      !value.includes("%") &&
      !value.includes(":") &&
      value.split("/").every((part) => part !== "." && part !== ".." && part.length > 0) &&
      ![...value].some((character) => character.charCodeAt(0) < 32),
  );
const boundedText = z.string().max(1024 * 1024);
const mediaType = z
  .string()
  .max(100)
  .regex(/^[a-zA-Z0-9.+-]+\/[a-zA-Z0-9.+-]+$/)
  .default("text/plain");
const cap = (
  toolId: string,
  provider: IntegrationProvider,
  effect: IntegrationCapability["effect"],
  inputSchema: z.ZodType,
  reconciliation = "Read target state and compare persisted action evidence before any retry.",
): IntegrationCapability => ({
  id: toolId,
  provider,
  effect,
  inputSchema,
  outputSchema: integrationOutputSchema(toolId),
  retryPolicy:
    toolId === "research.search"
      ? "reconcile_first"
      : effect === "read"
        ? "safe"
        : effect === "external_send"
          ? "never_automatic"
          : "reconcile_first",
  reconciliation,
});
export const toolCapabilities: IntegrationCapability[] = [
  ...googleWorkspaceCapabilities,
  cap(
    "research.search",
    "brave",
    "read",
    z.object({ query: z.string().min(1).max(2000), limit: z.number().int().min(1).max(20).default(10) }).strict(),
  ),
  cap("research.fetch", "research", "read", z.object({ url: z.url() }).strict()),
  cap("nextcloud.read", "nextcloud", "read", z.object({ path: relative }).strict()),
  cap("nextcloud.list", "nextcloud", "read", z.object({ path: relative.optional() }).strict()),
  cap(
    "nextcloud.write",
    "nextcloud",
    "external_draft",
    z
      .object({
        path: relative,
        content: boundedText,
        mediaType,
        expectedEtag: z.string().min(1).max(300).optional(),
        createOnly: z.boolean().default(false),
      })
      .strict()
      .refine((value) => value.createOnly || Boolean(value.expectedEtag), "Expected ETag or createOnly is required"),
  ),
  cap("nextcloud.mkdir", "nextcloud", "external_change", z.object({ path: relative }).strict()),
  cap(
    "nextcloud.move",
    "nextcloud",
    "external_change",
    z
      .object({
        path: relative,
        destinationPath: relative,
        expectedEtag: z.string().min(1).max(300),
      })
      .strict()
      .refine((v) => v.path !== v.destinationPath, "Distinct destination required"),
  ),
  cap(
    "gdrive.download",
    "gdrive",
    "read",
    z
      .object({
        fileId: id,
        expectedVersion: z.string().min(1).max(100),
        expectedSha256: z
          .string()
          .regex(/^[a-f0-9]{64}$/)
          .optional(),
        maxBytes: z
          .number()
          .int()
          .min(1)
          .max(1024 * 1024)
          .default(1024 * 1024),
      })
      .strict(),
  ),
  cap(
    "gdrive.revisions.read",
    "gdrive",
    "read",
    z
      .object({
        fileId: id,
        pageToken: z.string().min(1).max(2000).optional(),
        pageSize: z.number().int().min(1).max(100).default(100),
      })
      .strict(),
  ),
  cap("gdrive.read", "gdrive", "read", z.object({ fileId: id }).strict()),
  cap(
    "gdrive.create",
    "gdrive",
    "external_draft",
    z
      .object({
        folderId: id,
        name: z.string().min(1).max(255),
        content: boundedText,
        mediaType,
        predecessorId: id.optional(),
        expectedVersion: z.string().max(100).optional(),
      })
      .strict()
      .refine(
        (value) => !value.predecessorId || Boolean(value.expectedVersion),
        "Predecessor requires expectedVersion",
      ),
  ),
  cap("sevdesk.voucher.stage", "sevdesk", "external_draft", sevdeskVoucherStageSchema),
  cap("sevdesk.voucher.book", "sevdesk", "external_change", sevdeskVoucherBookSchema),
  cap("sevdesk.invoices.read", "sevdesk", "read", page),
  cap("sevdesk.vouchers.read", "sevdesk", "read", page),
  cap("sevdesk.transactions.read", "sevdesk", "read", page),
  cap("sevdesk.invoice.read", "sevdesk", "read", z.object({ invoiceId: id }).strict()),
  cap(
    "sevdesk.voucher.upload",
    "sevdesk",
    "external_draft",
    z
      .object({
        name: z
          .string()
          .min(1)
          .max(200)
          .regex(/^[\w. -]+$/),
        contentBase64: z
          .string()
          .max(1400000)
          .regex(/^[A-Za-z0-9+/]*={0,2}$/),
        mediaType: z.enum(["application/pdf", "image/jpeg", "image/png"]),
      })
      .strict(),
  ),
  cap("sevdesk.reminder.create", "sevdesk", "external_draft", z.object({ invoiceId: id }).strict()),
  cap(
    "sevdesk.reminder.send",
    "sevdesk",
    "external_send",
    z
      .object({ invoiceId: id, to: z.email(), subject: z.string().min(1).max(200), text: z.string().min(1).max(30000) })
      .strict(),
  ),
  cap("tactical.agents.read", "tactical", "read", empty),
  cap("tactical.alerts.read", "tactical", "read", empty),
  cap(
    "tactical.script.run",
    "tactical",
    "external_change",
    z
      .object({
        agentId: id,
        scriptId: z.number().int().positive(),
        timeoutSeconds: z.number().int().min(1).max(300).default(60),
      })
      .strict(),
  ),
  cap("proxmox.nodes.read", "proxmox", "read", empty),
  cap("proxmox.guests.read", "proxmox", "read", empty),
  cap(
    "proxmox.guest.action",
    "proxmox",
    "external_change",
    z
      .object({
        node: id,
        vmid: z.number().int().positive(),
        kind: z.enum(["qemu", "lxc"]),
        operation: z.enum(["start", "shutdown", "reboot"]),
      })
      .strict(),
  ),
  cap("proxmox.task.read", "proxmox", "read", z.object({ node: id, upid: z.string().min(1).max(1000) }).strict()),
  cap("graph.users.read", "graph", "read", empty),
  cap("graph.licenses.read", "graph", "read", empty),
  cap("graph.health.read", "graph", "read", empty),
  cap(
    "graph.user.licenses",
    "graph",
    "external_change",
    z.object({ userId: id, addSkuIds: z.array(z.uuid()).max(20), removeSkuIds: z.array(z.uuid()).max(20) }).strict(),
  ),
  cap(
    "graph.mail.send",
    "graph",
    "external_send",
    z
      .object({
        userId: id,
        to: z.array(z.email()).min(1).max(20),
        subject: z.string().min(1).max(200),
        text: z.string().min(1).max(30000),
      })
      .strict(),
  ),
  cap(
    "telegram.send",
    "telegram",
    "external_send",
    z.object({ chatId: z.string().regex(/^-?\d+$/), text: z.string().min(1).max(4096) }).strict(),
  ),
  cap(
    "discord.send",
    "discord",
    "external_send",
    z.object({ channelId: z.string().regex(/^\d+$/), text: z.string().min(1).max(2000) }).strict(),
  ),
];
const defaults: Partial<Record<IntegrationProvider, string>> = {
  brave: "https://api.search.brave.com",
  gdrive: "https://www.googleapis.com",
  sevdesk: "https://my.sevdesk.de/api/v1",
  graph: "https://graph.microsoft.com/v1.0",
  telegram: "https://api.telegram.org",
  discord: "https://discord.com/api/v10",
};
const sameScope = (a: IntegrationScope, b: IntegrationScope) =>
  a.companyId === b.companyId && a.areaId === b.areaId && a.customerId === b.customerId && a.projectId === b.projectId;
// Workflow brokers are short-lived. Account slots must outlive each service instance.
const accountActive = new Map<string, number>();
const accountWaiters = new Map<string, (() => void)[]>();
const canonical = (v: unknown): string => {
  if (v && typeof v === "object" && !Array.isArray(v))
    return JSON.stringify(
      Object.fromEntries(
        Object.entries(v)
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([k, value]) => [k, canonical(value)]),
      ),
    );
  return JSON.stringify(v) ?? "null";
};
const accountKey = (c: IntegrationConnection) =>
  createHash("sha256")
    .update(
      canonical({
        provider: c.provider,
        origin: new URL(c.baseUrl ?? defaults[c.provider] ?? "https://research.invalid").origin,
        identity: c.username ?? c.tokenId ?? c.oauth?.refreshTokenRef ?? c.secretRef ?? "anonymous",
      }),
    )
    .digest("hex");
export class IntegrationService {
  private readonly connections: Map<string, IntegrationConnection>;
  private readonly transport: HttpTransport;
  private readonly options: {
    connections: IntegrationConnection[];
    secrets: SecretResolver;
    meteredRequest?: MeteredIntegrationRequest;
    oauth?: OAuthTokenBroker;
    oauthGeneration?: (scope: IntegrationScope) => Promise<string | null>;
    authorize: (action: AuthorizedIntegrationAction) => Promise<void>;
    transport?: HttpTransport;
    sleep?: (ms: number) => Promise<void>;
  };
  constructor(options: {
    connections: IntegrationConnection[];
    secrets: SecretResolver;
    meteredRequest?: MeteredIntegrationRequest;
    oauth?: OAuthTokenBroker;
    oauthGeneration?: (scope: IntegrationScope) => Promise<string | null>;
    authorize: (action: AuthorizedIntegrationAction) => Promise<void>;
    transport?: HttpTransport;
    sleep?: (ms: number) => Promise<void>;
  }) {
    this.options = options;
    this.connections = new Map(options.connections.map((connection) => [connection.id, structuredClone(connection)]));
    this.transport = options.transport ?? defaultTransport;
    if (this.connections.size !== options.connections.length)
      throw new IntegrationError("configuration", "Connector-IDs müssen eindeutig sein.");
  }
  capabilities() {
    return [...this.connections.values()].map(({ id, provider, enabledTools, schemaTag, liveValidatedAt }) => ({
      id,
      provider,
      enabledTools,
      schemaTag,
      validation: liveValidatedAt ? "live" : "not_live_validated",
      liveValidatedAt,
    }));
  }
  async execute(input: AuthorizedIntegrationAction): Promise<IntegrationResult> {
    const action = structuredClone(input);
    if (!action.id || action.id.length > 300)
      throw new IntegrationError("validation", "Action-ID fehlt oder ist ungültig.");
    const connection = this.connections.get(action.targetId);
    const capability = toolCapabilities.find((item) => item.id === action.toolId);
    if (
      !connection ||
      !capability ||
      connection.provider !== capability.provider ||
      !connection.enabledTools.includes(action.toolId)
    )
      throw new IntegrationError("configuration", "Capability ist für dieses Ziel nicht eingerichtet.");
    if (!sameScope(action.scope, connection.scope))
      throw new IntegrationError("authorization", "Ziel liegt außerhalb des freigegebenen Bereichs.");
    const parsed = capability.inputSchema.safeParse(action.args);
    if (!parsed.success) throw new IntegrationError("validation", "Werkzeugargumente sind ungültig.");
    if (
      action.toolId === "research.search" &&
      (!this.options.meteredRequest || !integrationPriceSchema.safeParse(connection.pricing).success)
    )
      throw new IntegrationError(
        "configuration",
        "Suchkosten benötigen eine gültige administrative Preisversion und den Budgetbroker.",
      );
    // Authorize exact caller arguments before defaults are applied; this matches the persisted argument hash.
    await this.options.authorize(action);
    const args = parsed.data as Record<string, unknown>;
    const resource =
      (args.checkAccountId !== undefined ? `checkAccount:${args.checkAccountId}` : undefined) ??
      args.folderId ??
      args.userId ??
      args.agentId ??
      args.chatId ??
      args.channelId ??
      (args.vmid !== undefined ? `${args.node}/${args.vmid}` : undefined);
    if (resource !== undefined && (!connection.resourceIds || !connection.resourceIds.includes(String(resource))))
      throw new IntegrationError("authorization", "Zielressource ist nicht im Connector freigegeben.");
    // Reads by ID also cannot escape the administratively restricted resource list.
    if (args.fileId !== undefined && !connection.resourceIds?.includes(String(args.fileId)))
      throw new IntegrationError("authorization", "Datei ist nicht im Connector freigegeben.");
    const account = accountKey(connection);
    await this.acquire(account);
    try {
      await this.options.authorize(action);
      if (
        connection.oauth &&
        (!["gdrive", "graph"].includes(connection.provider) || !this.options.oauth || !this.options.oauthGeneration)
      )
        throw new IntegrationError("configuration", "OAuth ist für diesen Connector nicht eingerichtet.");
      const secret = connection.oauth
        ? await this.options.oauth!.accessToken(connection.oauth, {
            scope: action.scope,
            connectionId: connection.id,
            generation: await this.options.oauthGeneration!(action.scope),
            reason: `Action ${action.id}: ${action.toolId}`.slice(0, 300),
            authorize: () => this.options.authorize(action),
          })
        : connection.secretRef
          ? await this.options.secrets.resolve(
              connection.secretRef,
              `Action ${action.id}: ${action.toolId}`.slice(0, 300),
            )
          : "";
      if (!secret && connection.provider !== "research")
        throw new IntegrationError("configuration", "SecretRef oder gültiger Zugang fehlt.");
      await this.options.authorize(action);
      const result = await this.perform(connection, action, args, secret, capability);
      const validated = capability.outputSchema.safeParse(result);
      if (!validated.success)
        throw new IntegrationError(
          "provider",
          "Normalisierte Antwort erfüllt den Werkzeugvertrag nicht.",
          capability.effect === "read" ? "failed" : "effect_unknown",
        );
      return redact(validated.data as IntegrationResult, [
        secret,
        secret ? `Basic ${Buffer.from(`${connection.username ?? ""}:${secret}`).toString("base64")}` : "",
      ]);
    } finally {
      this.release(account);
    }
  }
  private async acquire(key: string) {
    if ((accountActive.get(key) ?? 0) >= 2)
      await new Promise<void>((resolve) => {
        const waiters = accountWaiters.get(key) ?? [];
        waiters.push(resolve);
        accountWaiters.set(key, waiters);
      });
    else accountActive.set(key, (accountActive.get(key) ?? 0) + 1);
  }
  private release(key: string) {
    const next = accountWaiters.get(key)?.shift();
    if (next) next();
    else {
      const count = (accountActive.get(key) ?? 1) - 1;
      if (count > 0) accountActive.set(key, count);
      else {
        accountActive.delete(key);
        accountWaiters.delete(key);
      }
    }
  }
  private async request(request: HttpRequest, writing: boolean): Promise<HttpResponse> {
    for (let attempt = 0; ; attempt++) {
      try {
        const result = await this.transport(request);
        checkResponse(result, writing);
        return result;
      } catch (error) {
        const failure =
          error instanceof IntegrationError
            ? error
            : new IntegrationError(
                "transport",
                "Providerverbindung fehlgeschlagen.",
                writing ? "effect_unknown" : "failed",
              );
        if (writing || attempt >= 2 || !["transport", "timeout", "rate_limit", "provider"].includes(failure.code))
          throw failure;
        const wait = Math.max(100 * 2 ** attempt + Math.floor(Math.random() * 50), failure.retryAfterMs ?? 0);
        // Do not ignore long server Retry-After values or occupy a worker for minutes.
        if (wait > 30000) throw failure;
        await (this.options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms))))(wait);
      }
    }
  }
  private async perform(
    c: IntegrationConnection,
    action: AuthorizedIntegrationAction,
    args: Record<string, unknown>,
    secret: string,
    capability: IntegrationCapability,
  ): Promise<IntegrationResult> {
    if (googleWorkspaceCapabilities.some((cap) => cap.id === action.toolId))
      return executeGoogleWorkspace({
        connection: c,
        action,
        token: secret,
        transport: this.transport,
        authorize: () => this.options.authorize(action),
      });
    const s = (key: string) => String(args[key]);
    const enc = (key: string) => encodeURIComponent(s(key));
    const writing = capability.effect !== "read";
    let base = c.baseUrl ?? defaults[c.provider];
    if (c.provider === "research") base = s("url");
    if (!base) throw new IntegrationError("configuration", "Connector-Endpunkt fehlt.");
    let endpoint: URL;
    try {
      endpoint = new URL(base);
    } catch {
      throw new IntegrationError("configuration", "Connector-Endpunkt ist ungültig.");
    }
    if (
      endpoint.username ||
      endpoint.password ||
      endpoint.search ||
      endpoint.hash ||
      (endpoint.protocol !== "https:" && !(c.allowHttp && c.provider !== "research" && endpoint.protocol === "http:"))
    ) {
      // Public research URLs may have queries; safe transport enforces URL/network rules separately.
      if (c.provider !== "research")
        throw new IntegrationError("configuration", "Connector benötigt HTTPS ohne URL-Zugangsdaten.");
    }
    const headers: Record<string, string> = { Accept: "application/json" };
    if (["gdrive", "graph"].includes(c.provider)) headers.Authorization = `Bearer ${secret}`;
    if (c.provider === "sevdesk") headers.Authorization = secret;
    if (c.provider === "tactical") headers["X-API-KEY"] = secret;
    if (c.provider === "proxmox") {
      if (!c.tokenId) throw new IntegrationError("configuration", "Proxmox-Token-ID fehlt.");
      headers.Authorization = `PVEAPIToken=${c.tokenId}=${secret}`;
    }
    if (c.provider === "discord") headers.Authorization = `Bot ${secret}`;
    if (c.provider === "brave") headers["X-Subscription-Token"] = secret;
    if (c.provider === "nextcloud") {
      if (!c.username || c.username.includes(":"))
        throw new IntegrationError("configuration", "Nextcloud-Benutzer fehlt oder ist ungültig.");
      headers.Authorization = `Basic ${Buffer.from(`${c.username}:${secret}`).toString("base64")}`;
    }
    let url = base.replace(/\/$/, "");
    let method = "GET";
    let body: string | Buffer | undefined;
    let expected: "json" | "text" | "empty" = "json";
    const json = (value: unknown) => {
      headers["Content-Type"] = "application/json";
      body = JSON.stringify(value);
    };
    const resultBase = {
      observedAt: new Date().toISOString(),
      effectStatus: "succeeded" as const,
      evidenceRefs: [] as string[],
    };
    switch (action.toolId) {
      case "research.search":
        url += `/res/v1/web/search?${new URLSearchParams({ q: s("query"), count: s("limit") })}`;
        break;
      case "research.fetch":
        url = base;
        expected = "text";
        break;
      case "nextcloud.read":
      case "nextcloud.list":
      case "nextcloud.mkdir":
      case "nextcloud.move":
      case "nextcloud.write": {
        const root = c.rootPath ?? "";
        if (root && !relative.safeParse(root).success)
          throw new IntegrationError("configuration", "Nextcloud-Zielpfad ist ungültig.");
        const path = [root, args.path].filter(Boolean).join("/").split("/").map(encodeURIComponent).join("/");
        url += `/remote.php/dav/files/${encodeURIComponent(c.username!)}/${path}`;
        expected = "text";
        if (action.toolId === "nextcloud.list") {
          method = "PROPFIND";
          headers.Depth = "1";
          headers["Content-Type"] = "application/xml";
          body =
            '<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:getetag/><d:getcontentlength/><d:resourcetype/></d:prop></d:propfind>';
        }
        if (action.toolId === "nextcloud.write") {
          method = "PUT";
          headers["Content-Type"] = s("mediaType");
          headers[args.createOnly ? "If-None-Match" : "If-Match"] = args.createOnly ? "*" : s("expectedEtag");
          body = s("content");
          expected = "empty";
        }
        if (action.toolId === "nextcloud.mkdir") {
          method = "MKCOL";
          headers["If-None-Match"] = "*";
          expected = "empty";
        }
        if (action.toolId === "nextcloud.move") {
          method = "MOVE";
          headers["If-Match"] = s("expectedEtag");
          headers.Overwrite = "F";
          const destination = [root, s("destinationPath")]
            .filter(Boolean)
            .join("/")
            .split("/")
            .map(encodeURIComponent)
            .join("/");
          headers.Destination = `${base.replace(/\/$/, "")}/remote.php/dav/files/${encodeURIComponent(c.username!)}/${destination}`;
          expected = "empty";
        }
        break;
      }
      case "gdrive.download": {
        const endpoint = `${url}/drive/v3/files/${enc("fileId")}`;
        const metadata = async () => {
          await this.options.authorize(action);
          const response = await this.request(
            { url: `${endpoint}?fields=id,version,mimeType,size`, headers, trustedEndpoint: true, maxBytes: 16384 },
            false,
          );
          const parsed = z
            .object({ id: z.string(), version: z.string(), mimeType: z.string(), size: z.string().regex(/^\d+$/) })
            .safeParse(this.parseJson(response, false));
          if (!parsed.success)
            throw new IntegrationError(
              "provider",
              "Dateimetadaten sind unvollständig; native Dokumente benötigen Export.",
            );
          const value = parsed.data;
          if (value.id !== s("fileId") || value.version !== s("expectedVersion"))
            throw new IntegrationError("conflict", "Dateiversion hat sich geändert.");
          if (
            value.mimeType.startsWith("application/vnd.google-apps.") ||
            BigInt(value.size) > BigInt(Number(args.maxBytes))
          )
            throw new IntegrationError(
              "validation",
              "Dateityp oder Dateigröße ist für diesen Download nicht zulässig.",
            );
          return value;
        };
        const before = await metadata();
        await this.options.authorize(action);
        const response = await this.request(
          { url: `${endpoint}?alt=media`, headers, trustedEndpoint: true, maxBytes: Number(args.maxBytes) },
          false,
        );
        const after = await metadata();
        const sha256 = createHash("sha256").update(response.body).digest("hex");
        if (
          before.mimeType !== after.mimeType ||
          before.size !== after.size ||
          BigInt(before.size) !== BigInt(response.body.length) ||
          (args.expectedSha256 && args.expectedSha256 !== sha256)
        )
          throw new IntegrationError("conflict", "Dateiinhalt passt nicht zur geprüften Version.");
        return {
          ...resultBase,
          externalId: s("fileId"),
          data: {
            fileId: s("fileId"),
            version: before.version,
            mediaType: before.mimeType,
            bytes: response.body.length,
            sha256,
            contentBase64: response.body.toString("base64"),
          },
        };
      }
      case "gdrive.revisions.read":
        url += `/drive/v3/files/${enc("fileId")}/revisions?${new URLSearchParams({ fields: "nextPageToken,revisions(id,mimeType,modifiedTime,keepForever,size,md5Checksum)", pageSize: s("pageSize"), ...(args.pageToken ? { pageToken: s("pageToken") } : {}) })}`;
        break;
      case "gdrive.read":
        url += `/drive/v3/files/${enc("fileId")}?fields=id,name,version,modifiedTime,mimeType,parents`;
        break;
      case "gdrive.create": {
        if (s("mediaType").startsWith("application/vnd.google-apps."))
          throw new IntegrationError("validation", "Native Google-Dokumente benötigen eine eigene Capability.");
        if (args.predecessorId) {
          const previous = await this.request(
            {
              url: `${url}/drive/v3/files/${enc("predecessorId")}?fields=id,version,parents`,
              headers,
              trustedEndpoint: true,
            },
            false,
          );
          const metadata = this.parseJson(previous, false) as { version?: string; parents?: string[] };
          if (String(metadata.version) !== s("expectedVersion") || !metadata.parents?.includes(s("folderId")))
            throw new IntegrationError("conflict", "Externe Dateiversion oder Zielordner hat sich geändert.");
        }
        const boundary = `ironcrew_${randomUUID()}`;
        method = "POST";
        url += "/upload/drive/v3/files?uploadType=multipart&fields=id,version,name,parents";
        headers["Content-Type"] = `multipart/related; boundary=${boundary}`;
        body = `--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({ name: s("name"), parents: [s("folderId")], appProperties: { ironcrewActionId: action.id, ...(args.predecessorId ? { predecessorId: s("predecessorId"), expectedVersion: s("expectedVersion") } : {}) } })}\r\n--${boundary}\r\nContent-Type: ${s("mediaType")}\r\n\r\n${s("content")}\r\n--${boundary}--\r\n`;
        break;
      }
      case "sevdesk.voucher.stage":
        url += "/Voucher/Factory/saveVoucher";
        method = "POST";
        json(voucherPayload(sevdeskVoucherStageSchema.parse(args)));
        break;
      case "sevdesk.voucher.book":
        url += `/Voucher/${enc("voucherId")}/bookAmount`;
        method = "PUT";
        json({
          amount: Number(args.amount),
          date: args.date,
          type: args.type,
          checkAccount: { id: args.checkAccountId, objectName: "CheckAccount" },
          checkAccountTransaction: { id: args.checkAccountTransactionId, objectName: "CheckAccountTransaction" },
          createFeed: true,
        });
        break;
      case "sevdesk.invoices.read":
      case "sevdesk.vouchers.read":
      case "sevdesk.transactions.read":
        url += `/${action.toolId === "sevdesk.invoices.read" ? "Invoice" : action.toolId === "sevdesk.vouchers.read" ? "Voucher" : "CheckAccountTransaction"}?${new URLSearchParams({ limit: String(args.limit ?? 100), offset: String(args.offset ?? 0), countAll: "true" })}`;
        break;
      case "sevdesk.invoice.read":
        url += `/Invoice/${enc("invoiceId")}`;
        break;
      case "sevdesk.voucher.upload": {
        method = "POST";
        url += "/Voucher/Factory/uploadTempFile";
        const boundary = `ironcrew_${randomUUID()}`;
        headers["Content-Type"] = `multipart/form-data; boundary=${boundary}`;
        body = Buffer.concat([
          Buffer.from(
            `--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${s("name")}"\r\nContent-Type: ${s("mediaType")}\r\n\r\n`,
          ),
          Buffer.from(s("contentBase64"), "base64"),
          Buffer.from(`\r\n--${boundary}--\r\n`),
        ]);
        break;
      }
      case "sevdesk.reminder.create":
        url += `/Invoice/Factory/createInvoiceReminder?${new URLSearchParams({ "invoice[id]": s("invoiceId"), "invoice[objectName]": "Invoice" })}`;
        method = "POST";
        json({ invoice: { id: s("invoiceId"), objectName: "Invoice" } });
        break;
      case "sevdesk.reminder.send":
        url += `/Invoice/${enc("invoiceId")}/sendViaEmail`;
        method = "POST";
        json({ toEmail: s("to"), subject: s("subject"), text: s("text") });
        break;
      case "tactical.agents.read":
        url += "/agents/";
        break;
      case "tactical.alerts.read":
        url += "/alerts/";
        break;
      case "tactical.script.run":
        url += `/agents/${enc("agentId")}/runscript/`;
        method = "POST";
        json({ script: args.scriptId, args: [], timeout: args.timeoutSeconds, output: "wait", run_as_user: false });
        break;
      case "proxmox.nodes.read":
        url += "/api2/json/nodes";
        break;
      case "proxmox.guests.read":
        url += "/api2/json/cluster/resources?type=vm";
        break;
      case "proxmox.guest.action":
        url += `/api2/json/nodes/${enc("node")}/${s("kind")}/${s("vmid")}/status/${s("operation")}`;
        method = "POST";
        break;
      case "proxmox.task.read":
        if (!c.resourceIds?.some((resource) => resource.startsWith(`${s("node")}/`)))
          throw new IntegrationError("authorization", "Node ist nicht freigegeben.");
        url += `/api2/json/nodes/${enc("node")}/tasks/${enc("upid")}/status`;
        break;
      case "graph.users.read":
        url += "/users?$select=id,displayName,userPrincipalName,assignedLicenses&$top=100";
        break;
      case "graph.licenses.read":
        url += "/subscribedSkus";
        break;
      case "graph.health.read":
        url += "/admin/serviceAnnouncement/healthOverviews";
        break;
      case "graph.user.licenses":
        url += `/users/${enc("userId")}/assignLicense`;
        method = "POST";
        json({
          addLicenses: (args.addSkuIds as string[]).map((skuId) => ({ skuId, disabledPlans: [] })),
          removeLicenses: args.removeSkuIds,
        });
        break;
      case "graph.mail.send":
        url += `/users/${enc("userId")}/sendMail`;
        method = "POST";
        json({
          message: {
            subject: s("subject"),
            body: { contentType: "Text", content: s("text") },
            toRecipients: (args.to as string[]).map((address) => ({ emailAddress: { address } })),
          },
          saveToSentItems: true,
        });
        expected = "empty";
        break;
      case "telegram.send":
        url += `/bot${secret}/sendMessage`;
        method = "POST";
        json({ chat_id: s("chatId"), text: s("text") });
        break;
      case "discord.send":
        url += `/channels/${enc("channelId")}/messages`;
        method = "POST";
        json({ content: s("text"), allowed_mentions: { parse: [] } });
        break;
      default:
        throw new IntegrationError("configuration", "Werkzeug ist nicht implementiert.");
    }
    const request: HttpRequest = {
      url,
      method,
      headers,
      body,
      trustedEndpoint: c.provider !== "research",
      maxBytes: 2 * 1024 * 1024,
    };
    const response =
      action.toolId === "research.search"
        ? await this.options.meteredRequest!({ action, connection: c, execute: () => this.transport(request) })
        : await this.request(request, writing);
    checkResponse(response, writing);
    const data =
      expected === "json"
        ? this.parseJson(response, writing)
        : expected === "empty"
          ? { status: response.status, etag: response.headers.etag }
          : response.body.toString("utf8");
    const obj = data && typeof data === "object" ? (data as Record<string, unknown>) : {};
    if (action.toolId === "research.search") {
      const parsed = z
        .object({
          web: z
            .object({
              results: z.array(
                z.object({
                  title: z.string(),
                  url: z.url(),
                  description: z.string().optional(),
                  page_age: z.string().optional(),
                }),
              ),
            })
            .optional(),
        })
        .passthrough()
        .safeParse(data);
      if (!parsed.success) throw new IntegrationError("provider", "Suchantwort hat ein unbekanntes Format.");
      return {
        ...resultBase,
        data: {
          sources: (parsed.data.web?.results ?? []).map((row) => ({
            url: row.url,
            title: row.title,
            excerpt: row.description ?? "",
            publishedAt: row.page_age,
            observedAt: resultBase.observedAt,
          })),
          query: s("query"),
        },
      };
    }
    if (action.toolId === "research.fetch")
      return {
        ...resultBase,
        data: { url, content: data, mediaType: response.headers["content-type"] ?? "text/plain" },
      };
    if (["nextcloud.mkdir", "nextcloud.move"].includes(action.toolId) && response.status !== 201)
      throw new IntegrationError("provider", "WebDAV bestätigte keine konfliktfreie Neuerstellung.", "effect_unknown");
    if (action.toolId === "gdrive.revisions.read") {
      const parsed = z
        .object({
          nextPageToken: z.string().max(2000).optional(),
          revisions: z
            .array(
              z.object({
                id: z.string(),
                mimeType: z.string().optional(),
                modifiedTime: z.string().optional(),
                keepForever: z.boolean().optional(),
                size: z.string().optional(),
                md5Checksum: z.string().optional(),
              }),
            )
            .max(100)
            .default([]),
        })
        .safeParse(data);
      if (!parsed.success) throw new IntegrationError("provider", "Revisionsantwort ist ungültig.");
      return {
        ...resultBase,
        externalId: s("fileId"),
        data: {
          items: parsed.data.revisions,
          nextCursor: parsed.data.nextPageToken ?? null,
          historyCompleteness: "provider_retained_only",
        },
      };
    }
    if (action.toolId === "nextcloud.list" && !String(data).includes("multistatus"))
      throw new IntegrationError("provider", "WebDAV antwortet nicht mit Multistatus.");
    if (action.toolId.startsWith("nextcloud."))
      return {
        ...resultBase,
        externalId: action.toolId === "nextcloud.move" ? headers.Destination : url,
        data: {
          content: data,
          etag: response.headers.etag,
          sha256: createHash("sha256")
            .update(action.toolId === "nextcloud.write" ? s("content") : response.body)
            .digest("hex"),
        },
      };
    if (action.toolId === "telegram.send") {
      const parsed = z
        .object({
          ok: z.literal(true),
          result: z.object({ message_id: z.number(), chat: z.object({ id: z.number() }) }),
        })
        .safeParse(data);
      if (!parsed.success)
        throw new IntegrationError("provider", "Telegram hat den Versand nicht bestätigt.", "effect_unknown");
      return {
        ...resultBase,
        effectStatus: "accepted",
        externalId: `${parsed.data.result.chat.id}:${parsed.data.result.message_id}`,
        data,
      };
    }
    if (action.toolId === "graph.mail.send")
      return { ...resultBase, effectStatus: "accepted", data: { accepted: true, delivered: false } };
    if (action.toolId === "proxmox.guest.action") {
      if (typeof obj.data !== "string" || !obj.data.startsWith("UPID:"))
        throw new IntegrationError("provider", "Externe Proxmox-Task-ID fehlt.", "effect_unknown");
      return { ...resultBase, effectStatus: "accepted", externalId: obj.data, data };
    }
    if (action.toolId === "gdrive.create" || action.toolId === "discord.send") {
      if (typeof obj.id !== "string" || !obj.id)
        throw new IntegrationError("provider", "Provider hat keine externe ID bestätigt.", "effect_unknown");
      return {
        ...resultBase,
        effectStatus: action.toolId === "discord.send" ? "accepted" : "succeeded",
        externalId: obj.id,
        data,
      };
    }
    if (
      c.provider === "sevdesk" &&
      ["sevdesk.voucher.stage", "sevdesk.voucher.book", "sevdesk.reminder.create", "sevdesk.reminder.send"].includes(
        action.toolId,
      )
    ) {
      const reference = action.toolId === "sevdesk.voucher.stage" ? obj.voucher : obj;
      const parsed = z
        .object({ id: z.union([z.string().min(1), z.number().int().positive()]), objectName: z.string() })
        .passthrough()
        .safeParse(reference);
      const expectedType =
        action.toolId === "sevdesk.voucher.stage"
          ? "Voucher"
          : action.toolId === "sevdesk.voucher.book"
            ? "VoucherLog"
            : action.toolId === "sevdesk.reminder.create"
              ? "Invoice"
              : "Email";
      if (!parsed.success || parsed.data.objectName !== expectedType)
        throw new IntegrationError(
          "provider",
          "sevdesk hat keine erwartete externe Ressource bestätigt.",
          "effect_unknown",
        );
      if (action.toolId === "sevdesk.voucher.stage" && String(parsed.data.status) !== "50")
        throw new IntegrationError("provider", "sevdesk hat keinen Belegentwurf bestätigt.", "effect_unknown");
      if (action.toolId === "sevdesk.voucher.book") {
        const voucher = z.object({ id: z.union([z.string(), z.number()]) }).safeParse(parsed.data.voucher);
        if (!voucher.success || String(voucher.data.id) !== s("voucherId"))
          throw new IntegrationError(
            "provider",
            "sevdesk-Buchungsbeleg passt nicht zur freigegebenen Rechnung.",
            "effect_unknown",
          );
      }
      return {
        ...resultBase,
        effectStatus: action.toolId === "sevdesk.reminder.send" ? "accepted" : "succeeded",
        externalId: String(parsed.data.id),
        data,
      };
    }
    if (c.provider === "sevdesk") {
      if (!Object.hasOwn(obj, "objects"))
        throw new IntegrationError(
          "provider",
          "sevdesk-Antwort enthält kein objects-Feld.",
          writing ? "effect_unknown" : "failed",
        );
      const objects = obj.objects;
      const first = Array.isArray(objects) ? objects[0] : objects;
      const reference = first && typeof first === "object" ? (first as Record<string, unknown>) : {};
      const externalId = reference.id
        ? String(reference.id)
        : typeof reference.filename === "string"
          ? reference.filename
          : undefined;
      if (writing && !externalId && action.toolId !== "sevdesk.reminder.send")
        throw new IntegrationError("provider", "sevdesk hat keine externe Referenz bestätigt.", "effect_unknown");
      if (
        action.toolId === "sevdesk.reminder.send" &&
        (!objects || (typeof objects === "object" && Object.keys(objects).length === 0))
      )
        throw new IntegrationError("provider", "sevdesk hat keine Versandannahme bestätigt.", "effect_unknown");
      return {
        ...resultBase,
        ...(action.toolId === "sevdesk.reminder.send" ? { effectStatus: "accepted" as const } : {}),
        externalId,
        data,
      };
    }
    if (c.provider === "proxmox" && !Object.hasOwn(obj, "data"))
      throw new IntegrationError("provider", "Proxmox-Antwort enthält kein data-Feld.");
    if (c.provider === "graph" && capability.effect === "read" && !Array.isArray(obj.value))
      throw new IntegrationError("provider", "Graph-Antwort enthält keine Datenliste.");
    if (c.provider === "tactical" && capability.effect === "read" && !Array.isArray(data))
      throw new IntegrationError("provider", "Tactical-Antwort enthält keine Datenliste.");
    return {
      ...resultBase,
      ...(action.toolId === "tactical.script.run" ? { effectStatus: "accepted" as const } : {}),
      data,
    };
  }
  private parseJson(response: HttpResponse, writing: boolean): unknown {
    try {
      return JSON.parse(response.body.toString("utf8"));
    } catch {
      throw new IntegrationError(
        "provider",
        "Provider lieferte kein gültiges JSON.",
        writing ? "effect_unknown" : "failed",
      );
    }
  }
}
