/** Original IronCrew character archetypes. Visual identity never grants skills or permissions. */
export const CHARACTER_SKINS = [
  {
    id: "navigator",
    name: "Navigator",
    description: "Navigatorin mit geflochtenem Haar, türkisfarbener Tunika und Tablet.",
    name_en: "Navigator",
    description_en: "Navigator with braided hair, a teal tunic and a tablet.",
  },
  {
    id: "engineer",
    name: "Ingenieur",
    description: "Techniker mit Irokesenschnitt, Bart und Werkzeuggürtel.",
    name_en: "Engineer",
    description_en: "Technician with a mohawk, beard and tool belt.",
  },
  {
    id: "sentinel",
    name: "Wächter",
    description: "Bärtiger Wächter mit breiter Schutzrüstung und Schild.",
    name_en: "Sentinel",
    description_en: "Bearded sentinel with broad protective armor and a shield.",
  },
  {
    id: "diplomat",
    name: "Diplomatin",
    description: "Langes bernsteinfarbenes Kleid und offene lange Haare.",
    name_en: "Diplomat",
    description_en: "Long amber dress and loose long hair.",
  },
  {
    id: "analyst",
    name: "Analyst",
    description: "Analyst mit Brille, Weste und Tablet im Rollstuhl.",
    name_en: "Analyst",
    description_en: "Analyst with glasses, waistcoat and tablet in a wheelchair.",
  },
  {
    id: "medic",
    name: "Medizinerin",
    description: "Weißer Kittel, hochgestecktes Haar und medizinischer Koffer.",
    name_en: "Medic",
    description_en: "White coat, hair in a bun and a medical case.",
  },
  {
    id: "pilot",
    name: "Pilotin",
    description: "Fluganzug mit Schultergurten und kompakter Ausrüstung.",
    name_en: "Pilot",
    description_en: "Flight suit with shoulder straps and compact equipment.",
  },
  {
    id: "ranger",
    name: "Kundschafter",
    description: "Leichte Reiseausrüstung mit asymmetrischem Umhang.",
    name_en: "Ranger",
    description_en: "Light travel gear with an asymmetrical cloak.",
  },
  {
    id: "archivist",
    name: "Archivar",
    description: "Graues zurückgekämmtes Haar, Weste, Gehstock und Buch.",
    name_en: "Archivist",
    description_en: "Gray swept-back hair, waistcoat, walking stick and book.",
  },
  {
    id: "artisan",
    name: "Gestalterin",
    description: "Afrofrisur, Arbeitsschürze und Pinsel mit Farbakzenten.",
    name_en: "Artisan",
    description_en: "Afro hairstyle, work apron and paintbrush with colorful accents.",
  },
  {
    id: "strategist",
    name: "Stratege",
    description: "Bärtiger Stratege mit Glatze, Maßanzug und Aktentasche.",
    name_en: "Strategist",
    description_en: "Bald, bearded strategist with a tailored suit and briefcase.",
  },
  {
    id: "courier",
    name: "Kurier",
    description: "Bewegliche Silhouette mit kompakter Umhängetasche.",
    name_en: "Courier",
    description_en: "Agile silhouette with a compact shoulder bag.",
  },
  {
    id: "diver",
    name: "Taucher",
    description: "Druckanzug mit rundem Helm und maritimen Details.",
    name_en: "Diver",
    description_en: "Pressure suit with a round helmet and maritime details.",
  },
  {
    id: "mechanic",
    name: "Mechaniker",
    description: "Afrofrisur, Bart, robuster Overall und Schraubenschlüssel.",
    name_en: "Mechanic",
    description_en: "Afro hairstyle, beard, sturdy overalls and a wrench.",
  },
  {
    id: "botanist",
    name: "Botanikerin",
    description: "Feldkleidung mit grünen Akzenten und Pflanzentasche.",
    name_en: "Botanist",
    description_en: "Field clothing with green accents and a plant bag.",
  },
  {
    id: "android",
    name: "Androide",
    description: "Glatte synthetische Figur mit sichtbaren Gelenken.",
    name_en: "Android",
    description_en: "Smooth synthetic character with visible joints.",
  },
  {
    id: "automaton",
    name: "Automat",
    description: "Eigenständiger kompakter Roboter mit mechanischem Körper.",
    name_en: "Automaton",
    description_en: "Original compact robot with a mechanical body.",
  },
  {
    id: "visitor",
    name: "Besucher",
    description: "Fremdartige Figur mit langem Kopf und eigener Anatomie.",
    name_en: "Visitor",
    description_en: "Alien character with an elongated head and distinct anatomy.",
  },
  {
    id: "cephalid",
    name: "Cephalid",
    description: "Nichtmenschliche Figur mit Tentakelsilhouette.",
    name_en: "Cephalid",
    description_en: "Nonhuman character with a tentacled silhouette.",
  },
  {
    id: "crystalline",
    name: "Kristallwesen",
    description: "Facettierter Körper aus klaren geometrischen Formen.",
    name_en: "Crystalline being",
    description_en: "Faceted body made of clear geometric shapes.",
  },
] as const;
export type CharacterSkinId = (typeof CHARACTER_SKINS)[number]["id"];
export const CHARACTER_SKIN_IDS = CHARACTER_SKINS.map((skin) => skin.id);
