/**
 * IronCrew — OIDC login, tested against real signatures.
 *
 * Every ID token in this file is a real JWS over a real keypair generated by
 * `node:crypto`, and the provider verifies it with the same code an
 * installation runs. Nothing about the verification is stubbed: a test that
 * mocked the signature check would pass just as happily against a provider
 * that skipped it, which is the one bug that matters most here.
 *
 * The suite is mostly adversarial on purpose. The happy path is three
 * assertions; the rest are the things an attacker sends — a token for another
 * audience, a token from another issuer, an expired one, one with no nonce, a
 * replayed callback, a signature from a key the issuer never published, an
 * `alg` of "none" — plus the case migration 0024 exists for: a perfectly
 * valid token for a subject nobody linked.
 *
 * No socket is opened. `fetchImpl` is injected and answers from a small
 * routing table, and the clock is injected so expiry is a variable rather
 * than a wait.
 */

import { describe, expect, it } from "vitest";
import { createHash, createHmac, createSign, generateKeyPairSync, type KeyObject } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { createTestDb } from "../domain/test-db.ts";
import { UserStore } from "./user-store.ts";
import {
  JWKS_REFRESH_COOLDOWN_MS,
  OidcError,
  OidcIdentityStore,
  OidcProvider,
  PENDING_LOGIN_TTL_MS,
  type OidcLoginResult,
  type OidcProviderConfig,
  type PendingLogin,
} from "./oidc-provider.ts";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** A trailing-slash-free issuer; the slash case gets its own test. */
const ISSUER = "https://auth.example.test/application/o/ironcrew";
const CLIENT_ID = "ironcrew-command-center";

/**
 * One constant for the client secret and one for the code, so "did this
 * message leak a credential?" is a substring check rather than a judgement.
 */
const CLIENT_SECRET = "client-secret-that-must-never-appear-anywhere";
const CODE = "authorization-code-that-must-never-appear-anywhere";
const REDIRECT_URI = "https://crew.example.test/api/crew/auth/oidc/callback";

const SUBJECT = "8f3c1a2e-0000-4c1d-9e77-directory-subject";
const START = Date.UTC(2026, 0, 15, 12, 0, 0);

const OWNER_EMAIL = "owner@example.test";
const STAFF_EMAIL = "staff@example.test";
const PASSWORD = "a-perfectly-fine-passphrase";

function sec(ms: number): number {
  return Math.floor(ms / 1000);
}

interface Signer {
  key: KeyObject;
  kid: string;
  alg: string;
  jwk: Record<string, unknown>;
}

/** Generated once: RSA keygen is the slowest thing in this file by far. */
function rsaSigner(kid: string): Signer {
  const { publicKey, privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  const jwk = { ...publicKey.export({ format: "jwk" }), kid, alg: "RS256", use: "sig" };
  return { key: privateKey, kid, alg: "RS256", jwk: jwk as Record<string, unknown> };
}

function ecSigner(kid: string): Signer {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = { ...publicKey.export({ format: "jwk" }), kid, alg: "ES256", use: "sig" };
  return { key: privateKey, kid, alg: "ES256", jwk: jwk as Record<string, unknown> };
}

const KEY_A = rsaSigner("key-a");
const KEY_B = rsaSigner("key-b");
const KEY_EC = ecSigner("key-ec");

function b64urlJson(value: unknown): string {
  return Buffer.from(JSON.stringify(value), "utf8").toString("base64url");
}

/**
 * Signs a real JWS.
 *
 * ECDSA uses `ieee-p1363` because JWS wants the raw r‖s pair, not the DER
 * sequence Node produces by default — getting that wrong is a signature that
 * fails for reasons unrelated to what a test is asserting.
 */
function signJwt(claims: Record<string, unknown>, signer: Signer, headerPatch: Record<string, unknown> = {}): string {
  const header = { alg: signer.alg, typ: "JWT", kid: signer.kid, ...headerPatch };
  const signingInput = `${b64urlJson(header)}.${b64urlJson(claims)}`;
  const signature = signer.alg.startsWith("ES")
    ? createSign("SHA256").update(signingInput).sign({ key: signer.key, dsaEncoding: "ieee-p1363" })
    : createSign("RSA-SHA256").update(signingInput).sign(signer.key);
  return `${signingInput}.${signature.toString("base64url")}`;
}

// ---------------------------------------------------------------------------
// A fake identity provider
// ---------------------------------------------------------------------------

interface FakeIssuerState {
  discovery: Record<string, unknown> | null;
  discoveryStatus: number;
  jwks: { keys: unknown[] };
  /** Applied after the next JWKS fetch — models a key rotation mid-flight. */
  rotateTo: { keys: unknown[] } | null;
  tokenStatus: number;
  tokenBody: Record<string, unknown>;
  /** Set by each test right before the callback is completed. */
  idToken: string | null;
}

interface Harness {
  db: DatabaseSync;
  users: UserStore;
  identities: OidcIdentityStore;
  provider: OidcProvider;
  state: FakeIssuerState;
  calls: Array<{ url: string; init: RequestInit }>;
  callsTo(fragment: string): Array<{ url: string; init: RequestInit }>;
  clock(): number;
  advance(ms: number): void;
}

function defaultDiscovery(): Record<string, unknown> {
  return {
    issuer: ISSUER,
    authorization_endpoint: `${ISSUER}/authorize`,
    token_endpoint: `${ISSUER}/token`,
    jwks_uri: `${ISSUER}/jwks`,
    response_types_supported: ["code"],
    id_token_signing_alg_values_supported: ["RS256", "ES256"],
    code_challenge_methods_supported: ["S256"],
    token_endpoint_auth_methods_supported: ["client_secret_basic", "client_secret_post"],
  };
}

function harness(
  options: {
    config?: Partial<OidcProviderConfig>;
    discovery?: Record<string, unknown> | null;
    jwks?: { keys: unknown[] };
  } = {},
): Harness {
  const db = createTestDb();
  const state: FakeIssuerState = {
    discovery: options.discovery === undefined ? defaultDiscovery() : options.discovery,
    discoveryStatus: 200,
    jwks: options.jwks ?? { keys: [KEY_A.jwk] },
    rotateTo: null,
    tokenStatus: 200,
    tokenBody: {},
    idToken: null,
  };
  const calls: Array<{ url: string; init: RequestInit }> = [];
  let clock = START;

  const fetchImpl = (async (url: string | URL | Request, init?: RequestInit) => {
    const asString = String(url);
    calls.push({ url: asString, init: init ?? {} });

    const answer = (status: number, body: unknown) =>
      ({
        ok: status < 400,
        status,
        text: async () => (typeof body === "string" ? body : JSON.stringify(body)),
      }) as unknown as Response;

    if (asString.includes("/.well-known/openid-configuration")) {
      if (state.discovery === null) return answer(state.discoveryStatus === 200 ? 404 : state.discoveryStatus, "");
      return answer(state.discoveryStatus, state.discovery);
    }
    if (asString.endsWith("/jwks")) {
      const served = state.jwks;
      if (state.rotateTo) {
        state.jwks = state.rotateTo;
        state.rotateTo = null;
      }
      return answer(200, served);
    }
    if (asString.endsWith("/token")) {
      const body =
        Object.keys(state.tokenBody).length > 0
          ? state.tokenBody
          : { access_token: "an-access-token", token_type: "Bearer", id_token: state.idToken };
      return answer(state.tokenStatus, body);
    }
    return answer(404, { error: "not_found" });
  }) as unknown as typeof fetch;

  const provider = new OidcProvider(
    {
      issuer: ISSUER,
      clientId: CLIENT_ID,
      clientSecret: CLIENT_SECRET,
      redirectUri: REDIRECT_URI,
      ...options.config,
    },
    { db, fetchImpl, now: () => clock },
  );

  return {
    db,
    users: new UserStore(db),
    identities: new OidcIdentityStore(db),
    provider,
    state,
    calls,
    callsTo: (fragment) => calls.filter((c) => c.url.includes(fragment)),
    clock: () => clock,
    advance: (ms) => {
      clock += ms;
    },
  };
}

/** An owner (so the installation is past bootstrap) plus a staff account. */
async function seedAccounts(h: Harness): Promise<{ owner: string; staff: string }> {
  const owner = await h.users.create({ email: OWNER_EMAIL, password: PASSWORD, role: "owner" });
  const staff = await h.users.create({ email: STAFF_EMAIL, password: PASSWORD, role: "operator" });
  return { owner: owner.id, staff: staff.id };
}

interface LoginOptions {
  claims?: Record<string, unknown>;
  signer?: Signer;
  headerPatch?: Record<string, unknown>;
  /** Replaces the whole token — for hand-built "alg: none" style forgeries. */
  rawToken?: string;
  /** What comes back in the callback's `state` parameter. */
  stateParam?: string;
  pendingPatch?: Partial<PendingLogin>;
  issuerParam?: string;
}

/** begin → mint the ID token the fake issuer will return → complete. */
async function login(h: Harness, opts: LoginOptions = {}): Promise<{ result: OidcLoginResult; pending: PendingLogin }> {
  const begun = await h.provider.beginLogin();
  const pending = { ...begun.pending, ...opts.pendingPatch };
  const claims: Record<string, unknown> = {
    iss: ISSUER,
    sub: SUBJECT,
    aud: CLIENT_ID,
    exp: sec(h.clock() + 3_600_000),
    iat: sec(h.clock()),
    nonce: begun.pending.nonce,
    ...opts.claims,
  };
  h.state.idToken = opts.rawToken ?? signJwt(claims, opts.signer ?? KEY_A, opts.headerPatch);
  const result = await h.provider.completeLogin({
    code: CODE,
    state: opts.stateParam ?? begun.pending.state,
    pending,
    ...(opts.issuerParam !== undefined ? { issuer: opts.issuerParam } : {}),
  });
  return { result, pending };
}

/** Every refusal message is checked for these, everywhere. */
function expectNoSecrets(message: string): void {
  expect(message).not.toContain(CLIENT_SECRET);
  expect(message).not.toContain(CODE);
  expect(message).not.toContain("eyJ");
}

function refusal(result: OidcLoginResult): { reason: string; message: string } {
  if (result.ok) throw new Error(`expected a refusal, got a login for ${result.userId}`);
  expectNoSecrets(result.message);
  return { reason: result.reason, message: result.message };
}

// ---------------------------------------------------------------------------

describe("OidcProvider — configuration", () => {
  it("refuses a provisioning mode that would let the directory mint owners", () => {
    const db = createTestDb();
    expect(
      () =>
        new OidcProvider(
          {
            issuer: ISSUER,
            clientId: CLIENT_ID,
            redirectUri: REDIRECT_URI,
            // Deliberately cast: this configuration arrives as parsed JSON in
            // production, where the type guarantees nothing at all.
            provisioning: { mode: "create", role: "owner" as never },
          },
          { db },
        ),
    ).toThrow(OidcError);
  });

  it("refuses an issuer or redirect URI that is not an absolute URL", () => {
    const db = createTestDb();
    expect(
      () => new OidcProvider({ issuer: "auth.example.test", clientId: CLIENT_ID, redirectUri: REDIRECT_URI }, { db }),
    ).toThrow(OidcError);
    expect(() => new OidcProvider({ issuer: ISSUER, clientId: CLIENT_ID, redirectUri: "/callback" }, { db })).toThrow(
      OidcError,
    );
  });
});

describe("OidcProvider — discovery", () => {
  it("builds an authorization URL with PKCE S256 and fresh state and nonce", async () => {
    const h = harness();
    const first = await h.provider.beginLogin({ redirectTo: "/office" });
    const second = await h.provider.beginLogin();

    const url = new URL(first.authorizationUrl);
    expect(url.origin + url.pathname).toBe(`${ISSUER}/authorize`);
    expect(url.searchParams.get("response_type")).toBe("code");
    expect(url.searchParams.get("client_id")).toBe(CLIENT_ID);
    expect(url.searchParams.get("redirect_uri")).toBe(REDIRECT_URI);
    expect(url.searchParams.get("scope")).toContain("openid");
    expect(url.searchParams.get("code_challenge_method")).toBe("S256");
    expect(url.searchParams.get("state")).toBe(first.pending.state);
    expect(url.searchParams.get("nonce")).toBe(first.pending.nonce);
    expect(first.pending.redirectTo).toBe("/office");

    // The challenge is really the hash of the verifier we kept.
    const expected = createHash("sha256").update(first.pending.codeVerifier, "ascii").digest().toString("base64url");
    expect(url.searchParams.get("code_challenge")).toBe(expected);

    // Randomness: no two logins share state, nonce or verifier.
    expect(second.pending.state).not.toBe(first.pending.state);
    expect(second.pending.nonce).not.toBe(first.pending.nonce);
    expect(second.pending.codeVerifier).not.toBe(first.pending.codeVerifier);
    expect(first.pending.state.length).toBeGreaterThanOrEqual(43);

    // The verifier is a secret and must never travel in the URL.
    expect(first.authorizationUrl).not.toContain(first.pending.codeVerifier);
    expect(first.authorizationUrl).not.toContain(CLIENT_SECRET);
  });

  it("caches the discovery document and refetches it after the TTL", async () => {
    const h = harness({ config: { discoveryTtlMs: 60_000 } });
    await h.provider.beginLogin();
    await h.provider.beginLogin();
    expect(h.callsTo("openid-configuration")).toHaveLength(1);

    h.advance(60_001);
    await h.provider.beginLogin();
    expect(h.callsTo("openid-configuration")).toHaveLength(2);
  });

  it("refuses a discovery document that is missing an endpoint", async () => {
    const doc = defaultDiscovery();
    delete doc.token_endpoint;
    const h = harness({ discovery: doc });

    await expect(h.provider.beginLogin()).rejects.toThrow(/token_endpoint/);

    // The same failure through the callback is a refusal, not a throw.
    const result = await h.provider.completeLogin({
      code: CODE,
      state: "pending-state",
      pending: { state: "pending-state", nonce: "n", codeVerifier: "v", issuer: ISSUER, expiresAt: h.clock() + 60_000 },
    });
    expect(refusal(result).reason).toBe("discovery_invalid");
  });

  it("refuses a discovery document that names a different issuer", async () => {
    const doc = { ...defaultDiscovery(), issuer: "https://someone-else.example.test" };
    const h = harness({ discovery: doc });
    await expect(h.provider.beginLogin()).rejects.toThrow(/someone-else\.example\.test/);
  });

  it("refuses plaintext endpoints that are not loopback, and accepts loopback ones", async () => {
    const overTheWire = harness({
      discovery: { ...defaultDiscovery(), token_endpoint: "http://auth.example.test/token" },
    });
    await expect(overTheWire.provider.beginLogin()).rejects.toThrow(/https/);

    const dev = harness({
      config: { issuer: "http://127.0.0.1:9000/application/o/ironcrew" },
      discovery: {
        ...defaultDiscovery(),
        issuer: "http://127.0.0.1:9000/application/o/ironcrew",
        authorization_endpoint: "http://127.0.0.1:9000/authorize",
        token_endpoint: "http://127.0.0.1:9000/token",
        jwks_uri: "http://127.0.0.1:9000/jwks",
      },
    });
    await expect(dev.provider.beginLogin()).resolves.toBeTruthy();
  });

  it("refuses an issuer that would downgrade PKCE to plain", async () => {
    const h = harness({ discovery: { ...defaultDiscovery(), code_challenge_methods_supported: ["plain"] } });
    await expect(h.provider.beginLogin()).rejects.toThrow(/S256/);
  });

  it("refuses an issuer that signs only with algorithms this client does not accept", async () => {
    const h = harness({ discovery: { ...defaultDiscovery(), id_token_signing_alg_values_supported: ["HS256"] } });
    await expect(h.provider.beginLogin()).rejects.toThrow(/algorithms/);
  });

  it("treats the discovery document's issuer as canonical when only a trailing slash differs", async () => {
    const h = harness({ config: { issuer: `${ISSUER}/` } });
    await seedAccounts(h);
    const staff = h.users.byEmail(STAFF_EMAIL)!;
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff.id });

    const { result } = await login(h);
    expect(result.ok).toBe(true);
  });
});

describe("OidcProvider — the token exchange", () => {
  it("sends the code, the verifier and the secret in the body or the header, never in the URL", async () => {
    const h = harness();
    await seedAccounts(h);
    const staff = h.users.byEmail(STAFF_EMAIL)!;
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff.id });

    const { result, pending } = await login(h);
    expect(result.ok).toBe(true);

    const call = h.callsTo("/token")[0];
    expect(call.url).toBe(`${ISSUER}/token`);
    expect(call.url).not.toContain(CLIENT_SECRET);
    expect(call.url).not.toContain(CODE);

    const body = new URLSearchParams(String(call.init.body));
    expect(body.get("grant_type")).toBe("authorization_code");
    expect(body.get("code")).toBe(CODE);
    expect(body.get("redirect_uri")).toBe(REDIRECT_URI);
    expect(body.get("client_id")).toBe(CLIENT_ID);
    expect(body.get("code_verifier")).toBe(pending.codeVerifier);
    // Basic is the spec default and what the fake issuer advertises first.
    expect(body.get("client_secret")).toBeNull();

    const headers = call.init.headers as Record<string, string>;
    const decoded = Buffer.from(headers.authorization.replace("Basic ", ""), "base64").toString("utf8");
    expect(decoded).toBe(`${encodeURIComponent(CLIENT_ID)}:${encodeURIComponent(CLIENT_SECRET)}`);
  });

  it("falls back to client_secret_post when the issuer advertises only that", async () => {
    const h = harness({
      discovery: { ...defaultDiscovery(), token_endpoint_auth_methods_supported: ["client_secret_post"] },
    });
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    await login(h);
    const call = h.callsTo("/token")[0];
    expect(new URLSearchParams(String(call.init.body)).get("client_secret")).toBe(CLIENT_SECRET);
    expect((call.init.headers as Record<string, string>).authorization).toBeUndefined();
  });

  it("sends no client authentication at all for a public client", async () => {
    const h = harness({ config: { clientSecret: undefined } });
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    await login(h);
    const call = h.callsTo("/token")[0];
    expect(new URLSearchParams(String(call.init.body)).get("client_secret")).toBeNull();
    expect((call.init.headers as Record<string, string>).authorization).toBeUndefined();
    // PKCE is what protects a public client, and it is still there.
    expect(new URLSearchParams(String(call.init.body)).get("code_verifier")).toBeTruthy();
  });

  it("surfaces the OAuth error code but never the issuer's error_description", async () => {
    const h = harness();
    await seedAccounts(h);
    h.state.tokenStatus = 400;
    h.state.tokenBody = {
      error: "invalid_grant",
      // An issuer that echoes the request into its description — several do.
      error_description: `code ${CODE} rejected for client secret ${CLIENT_SECRET}`,
    };

    const { result } = await login(h);
    const refused = refusal(result);
    expect(refused.reason).toBe("token_exchange_failed");
    expect(refused.message).toContain("invalid_grant");
    expect(refused.message).not.toContain("rejected for client");
  });

  it("refuses a token response with no id_token", async () => {
    const h = harness();
    await seedAccounts(h);
    h.state.tokenBody = { access_token: "only-an-access-token", token_type: "Bearer" };

    const { result } = await login(h);
    expect(refusal(result).reason).toBe("token_exchange_failed");
  });
});

describe("OidcProvider — state, nonce and replay", () => {
  it("refuses a callback whose state does not match, before contacting the issuer", async () => {
    const h = harness();
    await seedAccounts(h);
    const { result } = await login(h, { stateParam: "a-state-from-somewhere-else" });
    expect(refusal(result).reason).toBe("state_mismatch");
    // The code was never sent anywhere: a CSRF callback costs nothing.
    expect(h.callsTo("/token")).toHaveLength(0);
  });

  it("refuses a second callback carrying the same state", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const begun = await h.provider.beginLogin();
    const claims = {
      iss: ISSUER,
      sub: SUBJECT,
      aud: CLIENT_ID,
      exp: sec(h.clock() + 3_600_000),
      iat: sec(h.clock()),
      nonce: begun.pending.nonce,
    };
    h.state.idToken = signJwt(claims, KEY_A);

    const first = await h.provider.completeLogin({ code: CODE, state: begun.pending.state, pending: begun.pending });
    expect(first.ok).toBe(true);

    const second = await h.provider.completeLogin({ code: CODE, state: begun.pending.state, pending: begun.pending });
    expect(refusal(second).reason).toBe("state_replayed");
    // And it stopped before spending another code at the token endpoint.
    expect(h.callsTo("/token")).toHaveLength(1);
  });

  it("refuses an ID token whose nonce was already spent by another login", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const first = await h.provider.beginLogin();
    const second = await h.provider.beginLogin();
    const claims = (nonce: string) => ({
      iss: ISSUER,
      sub: SUBJECT,
      aud: CLIENT_ID,
      exp: sec(h.clock() + 3_600_000),
      iat: sec(h.clock()),
      nonce,
    });

    h.state.idToken = signJwt(claims(first.pending.nonce), KEY_A);
    expect(
      (await h.provider.completeLogin({ code: CODE, state: first.pending.state, pending: first.pending })).ok,
    ).toBe(true);

    // A pending login whose nonce is one that has already been used — the
    // state is fresh, so only the nonce register can catch this.
    const reused: PendingLogin = { ...second.pending, nonce: first.pending.nonce };
    h.state.idToken = signJwt(claims(first.pending.nonce), KEY_A);
    const replay = await h.provider.completeLogin({ code: CODE, state: reused.state, pending: reused });
    expect(refusal(replay).reason).toBe("id_token_nonce_mismatch");
    expect(refusal(replay).message).toContain("already used");
  });

  it("refuses a pending login that has expired", async () => {
    const h = harness();
    await seedAccounts(h);
    const begun = await h.provider.beginLogin();
    h.advance(PENDING_LOGIN_TTL_MS + 1);

    const result = await h.provider.completeLogin({ code: CODE, state: begun.pending.state, pending: begun.pending });
    expect(refusal(result).reason).toBe("login_expired");
    expect(h.callsTo("/token")).toHaveLength(0);
  });

  it("refuses a callback that names a different issuer (RFC 9207 mix-up)", async () => {
    const h = harness();
    await seedAccounts(h);
    const { result } = await login(h, { issuerParam: "https://attacker.example.test" });
    expect(refusal(result).reason).toBe("callback_issuer_mismatch");
    expect(h.callsTo("/token")).toHaveLength(0);
  });

  it("refuses an ID token with no nonce, and one with someone else's", async () => {
    const h = harness();
    await seedAccounts(h);

    const absent = await login(h, { claims: { nonce: undefined } });
    expect(refusal(absent.result).reason).toBe("id_token_nonce_mismatch");

    const wrong = await login(h, { claims: { nonce: "a-nonce-from-another-login" } });
    expect(refusal(wrong.result).reason).toBe("id_token_nonce_mismatch");
  });
});

describe("OidcProvider — ID token verification", () => {
  it("refuses a token whose aud is another client", async () => {
    const h = harness();
    await seedAccounts(h);
    const { result } = await login(h, { claims: { aud: "some-other-client" } });
    expect(refusal(result).reason).toBe("id_token_audience_mismatch");
  });

  it("refuses a multi-audience token unless azp names this client", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const without = await login(h, { claims: { aud: [CLIENT_ID, "another-client"] } });
    expect(refusal(without.result).reason).toBe("id_token_audience_mismatch");

    const withAzp = await login(h, { claims: { aud: [CLIENT_ID, "another-client"], azp: CLIENT_ID } });
    expect(withAzp.result.ok).toBe(true);
  });

  it("refuses a token minted by another issuer", async () => {
    const h = harness();
    await seedAccounts(h);
    const { result } = await login(h, { claims: { iss: "https://auth.attacker.test/application/o/ironcrew" } });
    expect(refusal(result).reason).toBe("id_token_issuer_mismatch");
  });

  it("refuses an expired token, a token from the future, and a stale one", async () => {
    const h = harness();
    await seedAccounts(h);

    const expired = await login(h, {
      claims: { exp: sec(h.clock() - 3_600_000), iat: sec(h.clock() - 7_200_000) },
    });
    expect(refusal(expired.result).reason).toBe("id_token_expired");

    const future = await login(h, {
      claims: { iat: sec(h.clock() + 3_600_000), exp: sec(h.clock() + 7_200_000) },
    });
    expect(refusal(future.result).reason).toBe("id_token_timestamps_invalid");

    // `exp` is still in the future, but the token was minted far too long ago
    // for something that is supposed to be seconds old.
    const stale = await login(h, {
      claims: { iat: sec(h.clock() - 3_000_000), exp: sec(h.clock() + 3_600_000) },
    });
    expect(refusal(stale.result).reason).toBe("id_token_timestamps_invalid");
  });

  it("accepts a token that expires within the clock tolerance", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const { result } = await login(h, { claims: { exp: sec(h.clock() - 30_000) } });
    expect(result.ok).toBe(true);
  });

  it("refuses a token signed by a key the issuer never published", async () => {
    const h = harness();
    await seedAccounts(h);
    // Signed with B, but claiming to be A's key: the candidate is found and
    // the signature simply does not verify.
    const { result } = await login(h, { signer: { ...KEY_B, kid: KEY_A.kid } });
    expect(refusal(result).reason).toBe("id_token_signature_invalid");
  });

  it("refuses a token whose payload was edited after signing", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const begun = await h.provider.beginLogin();
    const original = signJwt(
      {
        iss: ISSUER,
        sub: "somebody-else",
        aud: CLIENT_ID,
        exp: sec(h.clock() + 3_600_000),
        iat: sec(h.clock()),
        nonce: begun.pending.nonce,
      },
      KEY_A,
    );
    const [header, , signature] = original.split(".");
    const forgedPayload = Buffer.from(
      JSON.stringify({
        iss: ISSUER,
        sub: SUBJECT,
        aud: CLIENT_ID,
        exp: sec(h.clock() + 3_600_000),
        iat: sec(h.clock()),
        nonce: begun.pending.nonce,
      }),
      "utf8",
    ).toString("base64url");
    h.state.idToken = `${header}.${forgedPayload}.${signature}`;

    const result = await h.provider.completeLogin({ code: CODE, state: begun.pending.state, pending: begun.pending });
    expect(refusal(result).reason).toBe("id_token_signature_invalid");
  });

  it('refuses "alg": "none" and the HS* family', async () => {
    const h = harness();
    await seedAccounts(h);

    const header = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" }), "utf8").toString("base64url");
    const payload = Buffer.from(
      JSON.stringify({
        iss: ISSUER,
        sub: SUBJECT,
        aud: CLIENT_ID,
        exp: sec(h.clock() + 3_600_000),
        iat: sec(h.clock()),
      }),
      "utf8",
    ).toString("base64url");
    const none = await login(h, { rawToken: `${header}.${payload}.` });
    expect(refusal(none.result).reason).toBe("id_token_alg_unsupported");

    // The classic confusion: HMAC the token with the client secret, which the
    // client itself holds, and hope it is verified as if it were the issuer.
    const hsHeader = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" }), "utf8").toString("base64url");
    const signingInput = `${hsHeader}.${payload}`;
    const mac = createHmac("sha256", CLIENT_SECRET).update(signingInput).digest("base64url");
    const hs = await login(h, { rawToken: `${signingInput}.${mac}` });
    expect(refusal(hs.result).reason).toBe("id_token_alg_unsupported");
  });

  it("refuses a token that is not a three-part JWS", async () => {
    const h = harness();
    await seedAccounts(h);
    const { result } = await login(h, { rawToken: "not-a-jwt-at-all" });
    expect(refusal(result).reason).toBe("id_token_malformed");
  });

  it("verifies an ES256 token as readily as an RS256 one", async () => {
    const h = harness({ jwks: { keys: [KEY_EC.jwk] } });
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    const { result } = await login(h, { signer: KEY_EC });
    expect(result.ok).toBe(true);
  });

  it("refetches the key set once for an unknown kid, so a rotation just works", async () => {
    const h = harness();
    await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: h.users.byEmail(STAFF_EMAIL)!.id });

    // The issuer has rotated to B; our cache still holds A only.
    h.state.rotateTo = { keys: [KEY_A.jwk, KEY_B.jwk] };
    const { result } = await login(h, { signer: KEY_B });
    expect(result.ok).toBe(true);
    expect(h.callsTo("/jwks")).toHaveLength(2);
  });

  it("refuses an unknown kid, and does not let it drive repeated refetches", async () => {
    const h = harness();
    await seedAccounts(h);

    const first = await login(h, { signer: { ...KEY_B, kid: "a-key-that-does-not-exist" } });
    expect(refusal(first.result).reason).toBe("id_token_key_unknown");
    const afterFirst = h.callsTo("/jwks").length;
    expect(afterFirst).toBe(2); // the initial fetch plus one forced refresh

    // A stream of forged kids inside the cooldown must not become a fetch
    // amplifier pointed at the identity provider.
    const second = await login(h, { signer: { ...KEY_B, kid: "another-key-that-does-not-exist" } });
    expect(refusal(second.result).reason).toBe("id_token_key_unknown");
    expect(h.callsTo("/jwks")).toHaveLength(afterFirst);

    // Past the cooldown one more refetch is allowed.
    h.advance(JWKS_REFRESH_COOLDOWN_MS + 1);
    const third = await login(h, { signer: { ...KEY_B, kid: "a-third-key-that-does-not-exist" } });
    expect(refusal(third.result).reason).toBe("id_token_key_unknown");
    expect(h.callsTo("/jwks")).toHaveLength(afterFirst + 1);
  });
});

describe("OidcProvider — account resolution", () => {
  it("resolves a linked (issuer, subject) to its crew account and records the login", async () => {
    const h = harness();
    const { staff } = await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff, emailAtLink: "old-address@example.test" });

    const { result } = await login(h, { claims: { email: "brand-new-address@example.test", email_verified: true } });
    expect(result).toMatchObject({ ok: true, userId: staff, issuer: ISSUER, subject: SUBJECT, link: "existing" });

    const row = h.identities.get(ISSUER, SUBJECT)!;
    expect(row.last_login_at).toBe(h.clock());
    // The email the directory reports today does not overwrite what was
    // recorded at link time, and does not move the account.
    expect(row.email_at_link).toBe("old-address@example.test");
    expect(h.users.get(staff)!.last_login_at).toBe(h.clock());
    expect(h.users.get(staff)!.email).toBe(STAFF_EMAIL);
  });

  it("refuses an unlinked subject by name, and creates nothing", async () => {
    const h = harness();
    await seedAccounts(h);
    const before = h.users.count();

    const { result } = await login(h, { claims: { email: OWNER_EMAIL, email_verified: true } });
    const refused = refusal(result);
    expect(refused.reason).toBe("subject_not_linked");
    // Migration 0024: an owner has to be able to act on this in ten seconds.
    expect(refused.message).toContain(SUBJECT);
    expect(refused.message).toContain(ISSUER);

    expect(h.users.count()).toBe(before);
    expect(h.identities.get(ISSUER, SUBJECT)).toBeNull();
    // And emphatically not the owner account whose address it presented.
    expect(h.identities.listForUser(h.users.byEmail(OWNER_EMAIL)!.id)).toHaveLength(0);
    if (!result.ok) expect(result.identity).toEqual({ issuer: ISSUER, subject: SUBJECT, email: OWNER_EMAIL });
  });

  it("refuses a linked identity whose account has been disabled", async () => {
    const h = harness();
    const { staff } = await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff });
    h.users.update(staff, { status: "disabled" });

    const { result } = await login(h);
    expect(refusal(result).reason).toBe("account_unavailable");
  });

  it("provisions nobody while the installation has no accounts at all", async () => {
    const h = harness({ config: { provisioning: { mode: "create" } } });
    const { result } = await login(h, { claims: { email: "first@example.test", email_verified: true } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    expect(h.users.count()).toBe(0);
  });
});

describe("OidcProvider — link-verified-email", () => {
  const config = { provisioning: { mode: "link-verified-email" as const } };

  it("links a new subject to the account with that verified address, once", async () => {
    const h = harness({ config });
    const { staff } = await seedAccounts(h);

    const first = await login(h, { claims: { email: STAFF_EMAIL, email_verified: true } });
    expect(first.result).toMatchObject({ ok: true, userId: staff, link: "email-verified" });
    expect(h.identities.get(ISSUER, SUBJECT)).toMatchObject({ user_id: staff, email_at_link: STAFF_EMAIL });
    expect(h.users.count()).toBe(2);

    // From here on the subject decides. The directory renaming the person's
    // address — even to the owner's — changes nothing.
    const second = await login(h, { claims: { email: OWNER_EMAIL, email_verified: true } });
    expect(second.result).toMatchObject({ ok: true, userId: staff, link: "existing" });
  });

  it("refuses to link on an unverified address", async () => {
    const h = harness({ config });
    await seedAccounts(h);
    const { result } = await login(h, { claims: { email: OWNER_EMAIL, email_verified: false } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    expect(h.identities.get(ISSUER, SUBJECT)).toBeNull();
  });

  it("refuses to link when no local account has that address, and never creates one", async () => {
    const h = harness({ config });
    await seedAccounts(h);
    const { result } = await login(h, { claims: { email: "nobody-here@example.test", email_verified: true } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    expect(h.users.count()).toBe(2);
  });

  it("refuses to link to a disabled account", async () => {
    const h = harness({ config });
    const { staff } = await seedAccounts(h);
    h.users.update(staff, { status: "disabled" });

    const { result } = await login(h, { claims: { email: STAFF_EMAIL, email_verified: true } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    expect(h.identities.get(ISSUER, SUBJECT)).toBeNull();
  });
});

describe("OidcProvider — create", () => {
  const config = { provisioning: { mode: "create" as const } };

  it("creates the account at the configured role and links it", async () => {
    const h = harness({ config });
    await seedAccounts(h);

    const { result } = await login(h, {
      claims: { email: "newcomer@example.test", email_verified: true, name: "New Comer" },
    });
    expect(result).toMatchObject({ ok: true, link: "created" });

    const created = h.users.byEmail("newcomer@example.test")!;
    expect(created.role).toBe("viewer");
    expect(created.display_name).toBe("New Comer");
    expect(h.identities.get(ISSUER, SUBJECT)!.user_id).toBe(created.id);
  });

  it("honours a configured non-owner role", async () => {
    const h = harness({ config: { provisioning: { mode: "create", role: "operator" } } });
    await seedAccounts(h);
    await login(h, { claims: { email: "newcomer@example.test", email_verified: true } });
    expect(h.users.byEmail("newcomer@example.test")!.role).toBe("operator");
  });

  it("refuses rather than adopting an account that already has that address", async () => {
    const h = harness({ config });
    await seedAccounts(h);
    const before = h.users.count();

    const { result } = await login(h, { claims: { email: OWNER_EMAIL, email_verified: true } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    // The whole point: email matching must not arrive through the back door.
    expect(h.identities.listForUser(h.users.byEmail(OWNER_EMAIL)!.id)).toHaveLength(0);
    expect(h.users.count()).toBe(before);
  });

  it("refuses to create an account from an unverified address", async () => {
    const h = harness({ config });
    await seedAccounts(h);
    const { result } = await login(h, { claims: { email: "newcomer@example.test", email_verified: false } });
    expect(refusal(result).reason).toBe("subject_not_linked");
    expect(h.users.byEmail("newcomer@example.test")).toBeNull();
  });
});

describe("OidcIdentityStore", () => {
  it("keeps one directory identity on at most one account, and unlinks on request", async () => {
    const h = harness();
    const { owner, staff } = await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff });

    // The composite primary key is the rule; re-linking elsewhere is an error
    // rather than a silent takeover of the account.
    expect(() => h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: owner })).toThrow();
    expect(h.identities.get(ISSUER, SUBJECT)!.user_id).toBe(staff);

    // A second directory, same person: allowed, and that is why this is a
    // table rather than two columns on crew_users.
    h.identities.link({ issuer: "https://other-idp.example.test", subject: SUBJECT, userId: staff });
    expect(h.identities.listForUser(staff)).toHaveLength(2);

    expect(h.identities.unlink(ISSUER, SUBJECT)).toBe(true);
    expect(h.identities.unlink(ISSUER, SUBJECT)).toBe(false);
    expect(h.identities.listForUser(staff)).toHaveLength(1);
  });

  it("drops link rows with the account they belong to", async () => {
    const h = harness();
    const { staff } = await seedAccounts(h);
    h.identities.link({ issuer: ISSUER, subject: SUBJECT, userId: staff });
    h.users.delete(staff);
    expect(h.identities.get(ISSUER, SUBJECT)).toBeNull();
  });
});
