// Trusted runner sources are embedded so the compiled release is self-contained.
export const gateSource =
  "// Trusted native-side gate. No workload can start before its cgroup membership is committed.\nimport {spawn} from 'node:child_process';\nlet text='';for await(const chunk of process.stdin){text+=chunk;if(text.length>131072)process.exit(120);}\nconst input=JSON.parse(text);\nif(input.go!==true||typeof input.executable!=='string'||!Array.isArray(input.argv))process.exit(121);\nconst child=spawn(input.executable,input.argv,{shell:false,env:{LANG:'C.UTF-8',TZ:'UTC'},stdio:['ignore',1,2,3,4]});\nchild.once('error',()=>process.exit(122));\nchild.once('close',(code)=>{process.exitCode=code??137;});\n";
export const supervisorSource =
  "// Runs INSIDE all namespaces/seccomp/cgroup constraints. Its output is untrusted and revalidated by the host.\nimport {spawn} from 'node:child_process';\nimport {cp,lstat,readdir,readFile,writeFile,mkdir} from 'node:fs/promises';\nimport path from 'node:path';\nimport {writeSync} from 'node:fs';\nconst request=JSON.parse(await readFile('/run/ironcrew-request.json','utf8'));\nawait cp('/input','/workspace',{recursive:true,dereference:false});\nconst child=spawn(request.command,request.argv,{cwd:'/workspace',shell:false,env:{PATH:'/usr/local/bin:/usr/bin:/bin',HOME:'/tmp/home',TMPDIR:'/tmp',LANG:'C.UTF-8',TZ:'UTC',NODE_OPTIONS:'',npm_config_offline:'true',npm_config_audit:'false',npm_config_fund:'false',npm_config_cache:'/tmp/npm-cache'},stdio:['ignore','pipe','pipe']});\nchild.stdout.pipe(process.stdout);child.stderr.pipe(process.stderr);\nconst exitCode=await new Promise(resolve=>{child.once('error',()=>resolve(127));child.once('close',code=>resolve(code??137));});\nlet bytes=0;const files=[];const visited=new Set();\nfunction safe(value){return value!==''&&!path.isAbsolute(value)&&!value.includes('\\\\')&&!value.includes('\\0')&&value.split('/').every(part=>part!==''&&part!=='.'&&part!=='..'&&!/^\\.env(?:\\.|$)|^\\.git$|^\\.ssh$|^\\.ironcrew$/i.test(part));}\nasync function collect(relative){\n if(visited.has(relative))return;visited.add(relative);\n if(relative&&!safe(relative))throw Error('unsafe_output');\n const absolute=path.join('/workspace',relative);const stat=await lstat(absolute);\n if(stat.isSymbolicLink()||(!stat.isDirectory()&&!stat.isFile())||(stat.isFile()&&stat.nlink!==1))throw Error('unsafe_output');\n if(stat.isDirectory()){for(const item of await readdir(absolute))await collect(relative?relative+'/'+item:item);return;}\n if(files.length>=request.maxFiles||(bytes+=stat.size)>request.maxOutputBytes)throw Error('output_limit');\n const content=await readFile(absolute);if(content.length!==stat.size)throw Error('output_changed');\n files.push({path:relative,base64:content.toString('base64')});\n}\ntry{\n for(const relative of request.outputPaths)await collect(relative==='.'?'':relative);\n const payload=JSON.stringify({version:1,exitCode,files});\n writeSync(3,payload);\n}catch(error){writeSync(3,JSON.stringify({version:1,exitCode:125,error:error.message,files:[]}));}\n";
export const seccompSource =
  "/* Architecture-bound deny filters: nested namespaces, kernel attack interfaces, tracing and tty injection. */\n#include <stddef.h>\n#include <stdio.h>\n#include <errno.h>\n#include <linux/audit.h>\n#include <linux/filter.h>\n#include <linux/seccomp.h>\n#include <linux/sched.h>\n#include <sys/syscall.h>\n#if defined(__aarch64__)\n#define EXPECTED_ARCH AUDIT_ARCH_AARCH64\n#elif defined(__x86_64__)\n#define EXPECTED_ARCH AUDIT_ARCH_X86_64\n#else\n#error Unsupported isolation architecture\n#endif\n#define DENY(n) BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,__NR_##n,0,1),BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ERRNO|EPERM)\nint main(void){\n struct sock_filter filter[]={\n  BPF_STMT(BPF_LD+BPF_W+BPF_ABS,offsetof(struct seccomp_data,arch)),\n  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,EXPECTED_ARCH,1,0),BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_KILL_PROCESS),\n  BPF_STMT(BPF_LD+BPF_W+BPF_ABS,offsetof(struct seccomp_data,nr)),\n#if defined(__x86_64__)\n  BPF_JUMP(BPF_JMP+BPF_JGE+BPF_K,0x40000000,0,1),BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_KILL_PROCESS),\n#endif\n  DENY(mount),DENY(umount2),DENY(pivot_root),DENY(chroot),DENY(setns),DENY(unshare),\n  DENY(bpf),DENY(perf_event_open),DENY(keyctl),DENY(add_key),DENY(request_key),\n  DENY(kexec_load),DENY(init_module),DENY(finit_module),DENY(delete_module),DENY(reboot),\n  DENY(swapon),DENY(swapoff),DENY(open_by_handle_at),DENY(userfaultfd),DENY(ptrace),\n  DENY(process_vm_readv),DENY(process_vm_writev),\n#ifdef __NR_clone3\n  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,__NR_clone3,0,1),BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ERRNO|ENOSYS),\n#endif\n  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,__NR_clone,0,4),\n  BPF_STMT(BPF_LD+BPF_W+BPF_ABS,offsetof(struct seccomp_data,args[0])),\n  BPF_JUMP(BPF_JMP+BPF_JSET+BPF_K,CLONE_NEWUSER|CLONE_NEWNS|CLONE_NEWPID|CLONE_NEWNET|CLONE_NEWIPC|CLONE_NEWUTS|CLONE_NEWCGROUP|CLONE_PTRACE,0,1),\n  BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ERRNO|EPERM),BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ALLOW),\n  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,__NR_ioctl,0,4),\n  BPF_STMT(BPF_LD+BPF_W+BPF_ABS,offsetof(struct seccomp_data,args[1])),\n  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,0x5412,1,0),BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K,0x541c,0,1),\n  BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ERRNO|EPERM),\n  BPF_STMT(BPF_RET+BPF_K,SECCOMP_RET_ALLOW)\n };\n if(fwrite(filter,sizeof(filter),1,stdout)!=1){return 1;}return 0;\n}\n";

export const syscallProbeSource = `#define _GNU_SOURCE
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <sys/uio.h>
int main(void){char from='x',to=0;struct iovec local={&to,1},remote={&from,1};errno=0;ssize_t result=process_vm_readv(getpid(),&local,1,&remote,1,0);if(result==-1&&errno==EPERM){puts("denied");return 0;}puts("allowed");return 1;}
`;
